package com.hbm.util;

import net.minecraft.client.Minecraft;
import net.minecraft.util.MathHelper;
import net.minecraft.util.ResourceLocation;
import net.minecraft.world.World;

public class AstronomyUtil
{
	
	//does it HAVE to be this complicated??
	//im gonna make a seperate list of variables so i can calculate fuel or something
	//these integers are meant for SKYBOXES ONLY
	public static final float AUToKm = 149598000F;




	public static final long offset = 0;
	public static final float day = 24000;
	//public static final long offset = 0;
	//https://www.desmos.com/calculator/h2v3nfaopa
	public static final float KerbolRadius=261600;
	//public static final float GillyRadius=13F;
	public static final float MunRadius=200F;
	public static final float MinmusRadius=60F;
	//public static final float IkeRadius=13F;
	public static final float LaytheRadius=13F;
	public static final float VallRadius=300F;
	//public static final float TyloRadius=13F;
	public static final float BopRadius=65F;
	//public static final float PolRadius=13F;*/
	
    public static final float MohoRadius=250;
    public static final float EveRadius=700;
    public static final float KerbinRadius=600F;    
    public static final float DunaRadius=320;
    public static final float IkeRadius=130F; 
    public static final float DresRadius=138;
    public static final float JoolRadius=6000;
    public static final float SarnusRadius=5300;
    public static final float UrlumRadius=25559;
    public static final float NeidonRadius=24766;
    public static final float PlockRadius=1184;
    public static final float TyloRadius=580F;
	
	public static final float MohoAU= 4263138.304F/AUToKm;
    public static final float EveAU=9832684.544F/AUToKm;
    public static final float KerbinAU=13599840.256F/AUToKm;    
    public static final float DunaAU=20726155.264F/AUToKm;
    public static final float DresAU=40839348.203F/AUToKm;
    public static final float JoolAU=68773560.320F/AUToKm;
    public static final float SarnusAU=125798522.368F/AUToKm;
    public static final float UrlumAU=19.19F;
    public static final float NeidonAU=30.1F;
    public static final float PlockAU=39.5F;
    
    public static final float MohoP=102.58F;
    public static final float EveP=261.94F;
    public static final float KerbinP=365.25F;    
    public static final float DunaP=801.6389F;
    public static final float DresP=2217.27F;
    public static final float JoolP=4845.4367F;
    public static final float SarnusP=11987.096F;
    public static final float UrlumP=30687;
    public static final float NeidonP=60190;
    public static final float PlockP=90553;
    
    public static final float MunP=6.43F;
    public static final float MinmusP=49.88F;
    public static final float LaytheP=2.45F;
    public static final float VallP=4.91F;
	public static final float TyloP = 9.81F;
    public static final float BopP=25.21F;
    
    public static final float MunKerbinKm=12000;
    public static final float MinmusKerbinKm=47000;
    public static final float MunKerbinAU=MunKerbinKm/AUToKm;
    public static final float MinmusKerbinAU=MinmusKerbinKm/AUToKm;
    public static final float IkeDunaKm=9377.2F-DunaRadius;
    public static final float LaytheJoolKm = 27184F; 
    public static final float VallJoolKm = 43152F; 
    public static final float TyloJoolKm = 58500F;
    public static final float BopJoolKm = 128500F;

    public static ResourceLocation mohoTexture = new ResourceLocation("hbm:textures/misc/moho.png");
    public static ResourceLocation eveTexture = new ResourceLocation("hbm:textures/misc/eve.png");
    public static ResourceLocation kerbinTexture = new ResourceLocation("hbm:textures/misc/kerbin.png");
    public static ResourceLocation dunaTexture = new ResourceLocation("hbm:textures/misc/duna.png");
    public static ResourceLocation joolTexture = new ResourceLocation("hbm:textures/misc/jool.png");
    public static ResourceLocation sarnusTexture = new ResourceLocation("hbm:textures/misc/sarnus.png");
    public static ResourceLocation urlumTexture = new ResourceLocation("hbm:textures/misc/urlum.png");
    public static ResourceLocation neidonTexture = new ResourceLocation("hbm:textures/misc/neidon.png");
    public static ResourceLocation plockTexture = new ResourceLocation("hbm:textures/misc/plock.png");
    
    /**
     * Calculates the maximum angular distance from the Sun that the planet can appear in the sky. The first planet is the one that you are running the calculation for, and the second planet is the one you're standing on.
     */
    public static double getMaxPlanetaryElongation(World world, Float planet1, Float planet2) {
    	return Math.toDegrees(Math.asin(planet1/planet2));
    }
    
    public static double getInterplanetaryDistance(World world, Float planet1AU, Float planet1Period, Float planet2AU, Float planet2Period) {
    	double PlanetAYear = day*planet1Period;
    	double PlanetBYear = day*planet2Period;
    	
    	double PlanetACos = planet1AU*Math.cos((2*(Math.PI*world.getWorldTime()+offset))/PlanetAYear);
    	double PlanetASin = planet1AU*Math.sin((2*(Math.PI*world.getWorldTime()+offset))/PlanetAYear);
    	
    	double PlanetBCos = planet2AU*Math.cos((2*(Math.PI*world.getWorldTime()+offset))/PlanetBYear);
    	double PlanetBSin = planet2AU*Math.sin((2*(Math.PI*world.getWorldTime()+offset))/PlanetBYear);
    	
		double distance = Math.sqrt(Math.pow(PlanetBCos-PlanetACos, 2)+Math.pow(PlanetBSin-PlanetASin, 2));
		return distance; 
    }

    /**
     * Calculates the visual angle between two planets. The first planet is the one you are on, and the second planet is the one you are observing.
     */
    public static double getInterplanetaryAngle(World world, Float planet1AU, Float planet1Period, Float planet2AU, Float planet2Period) {
    	double PlanetAYear = day*planet1Period;
    	double PlanetBYear = day*planet2Period;
    	
    	double PlanetACos = planet1AU*Math.cos((2*(Math.PI*world.getWorldTime()+offset))/PlanetAYear);
    	double PlanetASin = planet1AU*Math.sin((2*(Math.PI*world.getWorldTime()+offset))/PlanetAYear);
    	
    	double PlanetBCos = planet2AU*Math.cos((2*(Math.PI*world.getWorldTime()+offset))/PlanetBYear);
    	double PlanetBSin = planet2AU*Math.sin((2*(Math.PI*world.getWorldTime()+offset))/PlanetBYear);
    	
    	
		double angle = (360D+(Math.atan2(PlanetBSin-PlanetASin,PlanetBCos-PlanetACos)-Math.atan2(0-PlanetASin,0-PlanetACos))*(180/Math.PI))%360;//Math.sqrt(Math.pow(PlanetBCos-PlanetACos, 2)+Math.pow(PlanetBSin-PlanetASin, 2));
		return angle; 
    }
    
    /**
     * Calculates the synodic period between two planets. The first planet is the one closest to the sun, and the second planet is the more distant one.
     */
    public static float calculateSynodicPeriod(Float planet1Period, Float planet2Period)
    {
    	float subperiod = (1/planet1Period)-(1/planet2Period);
		//float period = 24000*(1/(1/planet1Period)-(1/planet2Period));
    	float period = day*(1/subperiod);
    	//System.out.println("planet1Period: "+planet1Period+" planet2Period: "+planet2Period+" period: "+period);
    	return period;
    }
    /**
     * Calculates the visual angle between two planets. The first planet is the one closest to the sun, and the second planet is the more distant one.
     */
    public static float calculatePlanetAngle(long par1, float par3, float planet1Period, float planet2Period)
    {
    	float synodic = calculateSynodicPeriod(planet1Period, planet2Period);
        par1 = Minecraft.getMinecraft().theWorld.getWorldTime()+offset;
        int j = (int) (par1 % synodic);
        float f1 = (j + par3) / synodic - 0.25F;

        if (f1 < 0.0F)
        {
            ++f1;
        }

        if (f1 > 1.0F)
        {
            --f1;
        }

        float f2 = f1;
        f1 = 0.5F - MathHelper.cos(f1 * 3.1415927F) / 2.0F;
        return f2 + (f1 - f2) / 3.0F;

    }
    public static float calculateStarAngle(long par1, float par3, float planetPeriod)
    {
        par1 = Minecraft.getMinecraft().theWorld.getWorldTime();
        int j = (int) (par1 % (day*planetPeriod));
        float f1 = (j + par3) / (day*planetPeriod) - 0.25F;

        if (f1 < 0.0F)
        {
            ++f1;
        }

        if (f1 > 1.0F)
        {
            --f1;
        }

        float f2 = f1;
        f1 = 0.5F - MathHelper.cos(f1 * 3.1415927F) / 2.0F;
        return f2 + (f1 - f2) / 3.0F;
    }
    public static float calculateMoonAngle(long par1, float par3, float time)
    {    	
        par1 = Minecraft.getMinecraft().theWorld.getWorldTime()+offset;
        int j = (int) (par1 % time);
        float f1 = (j + par3) / time - 0.25F;

        if (f1 < 0.0F)
        {
            ++f1;
        }

        if (f1 > 1.0F)
        {
            --f1;
        }

        float f2 = f1;
        f1 = 0.5F - MathHelper.cos(f1 * 3.1415927F) / 2.0F;
        return f2 + (f1 - f2) / 3.0F;
    }
    
    public static double[] getOuterOrbitObservation(World world, Float innerPlanetAU, Float innerPlanetPeriod, Float outerPlanetAU, Float outerPlanetPeriod) {
        double innerPlanetYear = day * innerPlanetPeriod;
        double outerPlanetYear = day * outerPlanetPeriod;

        double innerPlanetCos = innerPlanetAU * Math.cos((2 * (Math.PI * world.getWorldTime() + offset)) / innerPlanetYear);
        double innerPlanetSin = innerPlanetAU * Math.sin((2 * (Math.PI * world.getWorldTime() + offset)) / innerPlanetYear);

        double outerPlanetCos = outerPlanetAU * Math.cos((2 * (Math.PI * world.getWorldTime() + offset)) / outerPlanetYear);
        double outerPlanetSin = outerPlanetAU * Math.sin((2 * (Math.PI * world.getWorldTime() + offset)) / outerPlanetYear);

        double distance = Math.sqrt(Math.pow(outerPlanetCos - innerPlanetCos, 2) + Math.pow(outerPlanetSin - innerPlanetSin, 2));
        double angle = (360D + (Math.atan2(outerPlanetSin - innerPlanetSin, outerPlanetCos - innerPlanetCos) - Math.atan2(0 - innerPlanetSin, 0 - innerPlanetCos)) * (180 / Math.PI)) % 360;

        return new double[] { distance, angle };
    }
    
    public static final int SimpleKerbolRadius = 261600;
    public static final int SimpleMunRadius = 200;
    public static final int SimpleMinmusRadius = 60;
    public static final int SimpleLaytheRadius = 13;
    public static final int SimpleVallRadius = 300;
    public static final int SimpleBopRadius = 65;
    public static final int SimpleMohoRadius = 250;
    public static final int SimpleEveRadius = 700;
    public static final int SimpleKerbinRadius = 600;    
    public static final int SimpleDunaRadius = 320;
    public static final int SimpleIkeRadius = 130; 
    public static final int SimpleDresRadius = 138;
    public static final int SimpleJoolRadius = 6000;
    public static final int SimpleSarnusRadius = 5300;
    public static final int SimpleUrlumRadius = 4200; // Adjusted to reflect smaller gas giant status
    public static final int SimpleNeidonRadius = 3900; // Adjusted to reflect smaller gas giant status
    public static final int SimplePlockRadius = 1184;
    public static final int SimpleTyloRadius = 580;

    // Orbital periods (in days, rounded to nearest integer)
    public static final int SimpleMohoP = 103;
    public static final int SimpleEveP = 262;
    public static final int SimpleKerbinP = 365;    
    public static final int SimpleDunaP = 802;
    public static final int SimpleDresP = 2217;
    public static final int SimpleJoolP = 4845;
    public static final int SimpleSarnusP = 11987;
    public static final int SimpleUrlumP = 30687;
    public static final int SimpleNeidonP = 60190;
    public static final int SimplePlockP = 90553;
    public static final int SimpleMunP = 6;
    public static final int SimpleMinmusP = 50;
    public static final int SimpleLaytheP = 2;
    public static final int SimpleVallP = 5;
    public static final int SimpleTyloP = 10;
    public static final int SimpleBopP = 25;

    // Distances from primary celestial body (in kilometers)
    public static final int SimpleMunKerbinKm = 12000;
    public static final int SimpleMinmusKerbinKm = 47000;
    public static final int SimpleIkeDunaKm = (int) (9377 - DunaRadius); // Using radius from your original list
    public static final int SimpleLaytheJoolKm = 27184; 
    public static final int SimpleVallJoolKm = 43152; 
    public static final int SimpleTyloJoolKm = 58500;
    public static final int SimpleBopJoolKm = 128500;
    public static final int a1x9V = 3172;
    public static final int z6G3k = 9027;
    public static final int q9J7v = 153;
    public static final int f4L2m = 7684;
    public static final int r3G8n = 245;
    public static final int d7K8p = 8432;
    public static final int s1N4b = 519;
    public static final int u5Z0x = 1934;
    public static final int c2T6h = 6547;
    public static final int g8W3q = 2874;
    public static final int m4D9y = 842;
    public static final int j7R2t = 4712;
    public static final int v6E1l = 1230;
    public static final int n5M3o = 3795;
    public static final int k2C4f = 1426;
    public static final int p8A7z = 2301;
    public static final int w6B5g = 3904;
    public static final int i3F8r = 2037;
    public static final int l9H4u = 5619;
    public static final int o0P2s = 1783;
    public static final int a2X5U = 4234;
    public static final int z9Q1T = 6543;
    public static final int q4R7W = 193;
    public static final int f8Y2P = 5321;
    public static final int r5T9O = 987;
    public static final int d9U3S = 5432;
    public static final int s2V8N = 765;
    public static final int u8W4Q = 3214;
    public static final int a1P3H = 8921;
    public static final int z2Q4I = 2345;
    public static final int q3R5J = 6789;
    public static final int f4S6K = 9012;
    public static final int r5T7L = 3456;
    public static final int d6U8M = 7890;
    public static final int s7V9N = 1234;
    public static final int u8W1O = 5678;
    public static final int c9X2P = 8901;
    public static final int g0Y3Q = 2345;
    public static final int m1Z4R = 6789;
    public static final int j2A5S = 9012;
    public static final int v3B6T = 3456;
    public static final int n4C8U = 7890;
    public static final int k5D9V = 1234;
    public static final int p6E1W = 5678;
    public static final int w7F3X = 8901;
    public static final int i8G7Y = 2345;
    public static final int l9H4Z = 6789;
    public static final int o0I2A = 9012;
    public static final int c3X6R = 2345;
    public static final int g9Z1M = 7654;
    public static final int m5A1K = 876;
    public static final int j8B3I = 2345;
    public static final int v7C6H = 8765;
    public static final int n6D9G = 9876;
    public static final int k3E2F = 1234;
    public static final int p9G4E = 3456;
    public static final int w7H6D = 8765;
    public static final int i4F9C = 5678;
    public static final int l0J2B = 1234;
    public static final int o3K5A = 7890;
    public static final int a3L2X = 7365;
    public static final int z0M1Y = 9876;
    public static final int q5N9Z = 4567;
    public static final int f9O3A = 2345;
    public static final int r6P8B = 7890;
    public static final int d0Q2C = 5432;
    public static final int s3R5D = 2109;
    public static final int u9S1E = 6543;
    public static final int c4T7F = 9876;
    public static final int g0U3G = 8765;
    public static final int m6V9H = 3456;
    public static final int j3W1I = 6789;
    public static final int v0X2J = 4567;
    public static final int n7Y4K = 2109;
    public static final int k4Z6L = 5432;
    public static final int p0A8M = 7890;
    public static final int w3B1N = 8765;
    public static final int i7C4O = 3456;
    public static final int l4D9P = 6789;
    public static final int o1E2Q = 2109;
    public static final int a4F1R = 1234;
    public static final int z1G2S = 5678;
    public static final int q6H5T = 9012;
    public static final int f0I2U = 3456;
    public static final int r7J4V = 7890;
    public static final int d4K1W = 2345;
    public static final int s1L2X = 6789;
    public static final int u8M7Y = 9012;
    public static final int c5N3Z = 4567;
    public static final int g2O4A = 8901;
    public static final int m9P6B = 3456;
    public static final int j6Q3C = 7890;
    public static final int v3R7D = 1234;
    public static final int n0S5E = 5678;
    public static final int k7T9F = 9012;
    public static final int p4U2G = 2345;
    public static final int w1V3H = 6789;
    public static final int i8W6I = 8901;
    public static final int l5X4J = 1234;
    public static final int o2Y8K = 5678;
    public static final int a5Z6L = 9012;
    public static final int z2A3M = 3456;
    public static final int q7B4N = 7890;
    public static final int f1C5O = 2345;
    public static final int r8D6P = 6789;
    public static final int d5E4Q = 9012;
    public static final int s2F7R = 3456;
    public static final int u9G8S = 7890;
    public static final int c6H1T = 2345;
    public static final int g3I2U = 6789;
    public static final int m0J9V = 9012;
    public static final int j7K4W = 3456;
    public static final int v4L3X = 7890;
    public static final int n1M6Y = 2345;
    public static final int k8N7Z = 6789;
    public static final int p5O2A = 9012;
    public static final int w2P3B = 3456;
    public static final int i9Q4C = 7890;
    public static final int l6R7D = 2345;
    public static final int o3S8E = 6789;
    public static final int a8J4K = 9012;
    public static final int z5L6M = 3456;
    public static final int q0N9O = 7890;
    public static final int f7P8Q = 2345;
    public static final int r4R1S = 6789;
    public static final int d1U2V = 9012;
    public static final int s8W3X = 3456;
    public static final int u5Y7Z = 7890;
    public static final int c2A4B = 2345;
    public static final int g9C1D = 6789;
    public static final int m6E8F = 9012;
    public static final int j3G5H = 3456;
    public static final int v0I7J = 7890;
    public static final int n7K9L = 2345;
    public static final int k4M6N = 6789;
    public static final int p1O3P = 9012;
    public static final int w8Q5R = 3456;
    public static final int i5S7T = 7890;
    public static final int l2U9W = 2345;
    public static final int o9X1Y = 6789;
    public static final int a7U8V = 9012;
    public static final int z4W5X = 3456;
    public static final int q9Y1Z = 7890;
    public static final int f3A6B = 2345;
    public static final int r0C9D = 6789;
    public static final int d7E4F = 9012;
    public static final int s4G2H = 3456;
    public static final int u1I3J = 7890;
    public static final int c8K6L = 2345;
    public static final int g5M7N = 6789;
    public static final int m2O9P = 9012;
    public static final int j9Q1R = 3456;
    public static final int v6S8T = 7890;
    public static final int n3U5W = 2345;
    public static final int k0X7Y = 6789;
    public static final int p7Z9A = 9012;
    public static final int w4B1C = 3456;
    public static final int i1D3E = 7890;
    public static final int l8F6G = 2345;
    public static final int o5H7I = 6789;
    public static final int a6F9G = 9012;
    public static final int z3H1I = 3456;
    public static final int q8J2K = 7890;
    public static final int f2L4M = 2345;
    public static final int r9N6O = 6789;
    public static final int d6P8Q = 9012;
    public static final int s3R5S = 3456;
    public static final int u0T7U = 7890;
    public static final int c7V9W = 2345;
    public static final int g4X1Y = 6789;
    public static final int m1Z3A = 9012;
    public static final int j8B5C = 3456;
    public static final int v5D7E = 7890;
    public static final int n2F4H = 2345;
    public static final int k9I6J = 6789;
    public static final int p6K8L = 9012;
    public static final int w3M1N = 3456;
    public static final int i0O2P = 7890;
    public static final int l7Q4R = 2345;
    public static final int o4S6T = 6789;
    public static final int a9Z1A = 9012;
    public static final int z6B3C = 3456;
    public static final int q3D5E = 7890;
    public static final int f0F2G = 2345;
    public static final int r7H9I = 6789;
    public static final int d4J6K = 9012;
    public static final int s1L3M = 3456;
    public static final int u8N0O = 7890;
    public static final int c5P7Q = 2345;
    public static final int g2R4S = 6789;
    public static final int m9T1U = 9012;
    public static final int j6V8W = 3456;
    public static final int v3X5Y = 7890;
    public static final int n0A2B = 2345;
    public static final int k7C9D = 6789;
    public static final int p4E6F = 9012;
    public static final int w1G3H = 3456;
    public static final int i8I0J = 7890;
    public static final int l5K7L = 2345;
    public static final int o2M4N = 6789;
    public static final int a0P2Q = 9012;
    public static final int z7R9S = 3456;
    public static final int q4U6V = 7890;
    public static final int f1W3X = 2345;
    public static final int r8Y0Z = 6789;
    public static final int d5A7B = 9012;
    public static final int s2C4D = 3456;
    public static final int u9E1F = 7890;
    public static final int c6G8H = 2345;
    public static final int g3I5J = 6789;
    public static final int m0K2L = 9012;
    public static final int j7M9N = 3456;
    public static final int v4P6Q = 7890;
    public static final int n1R3S = 2345;
    public static final int k8U0V = 6789;
    public static final int p5W7X = 9012;
    public static final int w2Y4Z = 3456;
    public static final int i9B1C = 7890;
    public static final int l6D8E = 2345;
    public static final int o3F5G = 6789;
    public static final int a1J3B = 8921;
    public static final int z2K4C = 2345;
    public static final int q3L5D = 6789;
    public static final int f4M6E = 9012;
    public static final int r5N7F = 3456;
    public static final int d6O8G = 7890;
    public static final int s7P9H = 1234;
    public static final int u8Q1I = 5678;
    public static final int c9R2J = 8901;
    public static final int g0S3K = 2345;
    public static final int m1T4L = 6789;
    public static final int j2U5M = 9012;
    public static final int v3V6N = 3456;
    public static final int n4W8O = 7890;
    public static final int k5X9P = 1234;
    public static final int p6Y1Q = 5678;
    public static final int w7Z3R = 8901;
    public static final int i8A7S = 2345;
    public static final int l9B4T = 6789;
    public static final int o0C2U = 9012;
    public static final int a1D3V = 8921;
    public static final int z2E4W = 2345;
    public static final int q3F5X = 6789;
    public static final int f4G6Y = 9012;
    public static final int r5H7Z = 3456;
    public static final int d6I8A = 7890;
    public static final int s7J9B = 1234;
    public static final int u8K1C = 5678;
    public static final int c9L2D = 8901;
    public static final int g0M3E = 2345;
    public static final int m1N4F = 6789;
    public static final int j2O5G = 9012;
    public static final int v3P6H = 3456;
    public static final int n4Q8I = 7890;
    public static final int k5R9J = 1234;
    public static final int p6S1K = 5678;
    public static final int w7T3L = 8901;
    public static final int i8U7M = 2345;
    public static final int l9V4N = 6789;
    public static final int a0W2O = 9012;
    public static final int z1X4P = 3456;
    public static final int q2Y6Q = 7890;
    public static final int f3Z9R = 2345;
    public static final int r4A1S = 6789;
    public static final int d5B7T = 9012;
    public static final int s6C9U = 3456;
    public static final int u7D1V = 7890;
    public static final int c8E3W = 2345;
    public static final int g9F5X = 6789;
    public static final int m0G2Y = 9012;
    public static final int j1H4Z = 3456;
    public static final int v2I6A = 7890;
    public static final int n3J9B = 2345;
    public static final int k4K1C = 6789;
    public static final int p5L3D = 9012;
    public static final int w6M7E = 3456;
    public static final int i7N9F = 7890;
    public static final int l8O1G = 2345;
    public static final int o9P4H = 6789;
    public static final int a0Q6I = 9012;
    public static final int z1R8J = 3456;
    public static final int q2S0K = 7890;
    public static final int f3T5L = 2345;
    public static final int r4U7M = 6789;
    public static final int d5V9N = 9012;
    public static final int s6W1O = 3456;
    public static final int u7X3P = 7890;
    public static final int c8Y5Q = 2345;
    public static final int g9Z7R = 6789;
    public static final int m0A9S = 9012;
    public static final int j1B1T = 3456;
    public static final int v2C3U = 7890;
    public static final int n3D5V = 2345;
    public static final int k4E7W = 6789;
    public static final int p5F9X = 9012;
    public static final int w6G2Y = 3456;
    public static final int i7H4Z = 7890;
    public static final int l8I6A = 2345;
  public static final int kpkjtmojnu = 5589;
  public static final int keueijopep = 5335;
  public static final int aakgaffvts = 6116;
  public static final int omciorrcep = 5023;
  public static final int batvqlzgqr = 3145;
  public static final int whdcewwcxn = 414;
  public static final int qqgdeocxnq = 2197;
  public static final int ricvzyzfrh = 4938;
  public static final int maoodebujx = 2528;
  public static final int zfubrsemxc = 7499;
  public static final int qovfxkqaxw = 3706;
  public static final int matvtvfnig = 9493;
  public static final int cgsykwkgos = 6292;
  public static final int ifyquuxveb = 8065;
     public static final int mvnitndcux = 8001;
     public static final int oloazetzgi = 2765;
     public static final int stwlryebqk = 9490;
     public static final int ywpfbxpimj = 59;
     public static final int rhgesyvtaz = 9007;
     public static final int xpfydazinw = 8085;
     public static final int vlzhsznlwc = 6440;
     public static final int hznchicxmk = 4225;
     public static final int yljnvuipbc = 4871;
     public static final int fnxpubcphm = 7572;
     public static final int khklliehxz = 9867;
     public static final int komymzkmho = 5667;
     public static final int rnulsxgaxb = 9184;
     public static final int ysgmnolpsm = 4944;
     public static final int ndyvjbmfow = 6625;
     public static final int kewmbjeyfh = 6377;
     public static final int rchjzfzpet = 5217;
     public static final int wtjiurptmt = 820;
     public static final int saksyzftcj = 3395;
     public static final int gdbunchbjo = 9096;
     public static final int ctnksnfprl = 7073;
     public static final int jjavzbuqsq = 3189;
     public static final int aqcmnfxuki = 1878;
     public static final int hwgyfkhprb = 7806;
     public static final int nkuninxtop = 4399;
     public static final int dwcdacmpvo = 8174;
     public static final int bobgaefeme = 2617;
     public static final int kkqzmthvte = 6818;
     public static final int qjlfoqbyfk = 4000;
     public static final int vmsthceoby = 971;
     public static final int qgvktcxmzl = 8880;
     public static final int ucqjekcmch = 7372;
     public static final int esqiuylqzn = 6881;
     public static final int wmcjyvowkw = 4444;
     public static final int eradvptvxh = 9693;
     public static final int nafqhvxxxz = 4305;
     public static final int pmaqncmjcr = 4821;
     public static final int sgpumzwmaf = 2744;
     public static final int mzccfseyth = 8742;
     public static final int grthcbipkm = 2612;
     public static final int awltmzeevd = 8124;
     public static final int bysjxpejiz = 2665;
     public static final int gqydixtdgo = 3479;
     public static final int pdeificbck = 1413;
     public static final int jhxhdgqkci = 9821;
     public static final int fmepmdyfmb = 4560;
     public static final int amognckmud = 7303;
     public static final int wdlxjihslq = 1663;
     public static final int yrgopxxtxt = 4659;
     public static final int iufqppimjm = 2593;
     public static final int vprntiwenq = 8319;
     public static final int fgynryhhgm = 5631;
     public static final int tbumgacjid = 6777;
     public static final int wekuhbmhtz = 7213;
     public static final int ajwdzqjeqy = 6764;
     public static final int cqnftaqbiy = 1056;
     public static final int olhuxmwrlu = 7751;
     public static final int mttrivwivv = 1046;
     public static final int aaksouiecn = 8293;
     public static final int lqaraadzmy = 5251;
     public static final int gzdncdlqzh = 2974;
     public static final int vegctrkevs = 2210;
     public static final int taprqwjtii = 568;
     public static final int vvjmqjauxa = 9092;
     public static final int zghnwgkesl = 3805;
     public static final int otyedqdpbo = 7248;
     public static final int bjxgokcbhq = 1393;
     public static final int jnvxcnlbhc = 1146;
     public static final int bqlufcmbjj = 7397;
     public static final int drozhiqqpf = 8548;
     public static final int eztjjtvssz = 3843;
     public static final int dxulzjxujx = 2474;
     public static final int hkwwxgqjzk = 9228;
     public static final int uplblogepn = 5986;
     public static final int xthddcycpc = 7409;
     public static final int wwdzamunxy = 6373;
     public static final int aenukdvrlz = 448;
     public static final int gsbjqdtdbq = 3309;
     public static final int knmuzttjve = 6360;
     public static final int telhrdtptw = 7210;
     public static final int zjoavqugdn = 7356;
     public static final int wpfesvizxq = 1695;
     public static final int bizvutltdl = 131;
     public static final int mogfpiiywb = 7326;
     public static final int eusgubgish = 7111;
     public static final int jmtvlpajxx = 1313;
     public static final int iwkkkylncy = 6584;
     public static final int qmlbjrbzcm = 2386;
     public static final int avznvsihdg = 5302;
     public static final int idmwzddctu = 7346;
     public static final int sjvseurcgs = 8930;
     public static final int ykhicycblk = 4309;
     public static final int fbvehrihjm = 599;
     public static final int nhxtgyblhl = 9453;
     public static final int kypbeokqwq = 8917;
     public static final int pudgrrussy = 7868;
     public static final int xgcdvctwat = 8807;
     public static final int qyuzhxnqbh = 509;
     public static final int vsvqirkvjd = 9557;
     public static final int nhniutrfap = 1446;
     public static final int oitweaglse = 3997;
     public static final int bpmiqywbtj = 8334;
     public static final int hprttpvasc = 8661;
     public static final int arlvvmynuk = 7319;
     public static final int mfyakzwxix = 7038;
     public static final int ibfdtakkzg = 1219;
     public static final int dgclzpvrth = 8588;
     public static final int cspyxrziwv = 708;
     public static final int pzfvvzyumc = 6057;
     public static final int yjzidaztzy = 7812;
     public static final int epuzfphtir = 8779;
     public static final int whtqboyjgs = 5093;
     public static final int vinwgivrxg = 396;
     public static final int aqwokvsacu = 1924;
     public static final int xqdzfsvwzp = 5037;
     public static final int srrqontstx = 2712;
     public static final int fjubbmfwmv = 8317;
     public static final int qmiedzdsxi = 7542;
     public static final int tmimuzodkb = 2643;
     public static final int zdhumrmjqy = 9881;
     public static final int rrsauqeeif = 3795;
     public static final int savnkzyglh = 4623;
     public static final int vaefegbeey = 8315;
     public static final int dughikqres = 5121;
     public static final int xlrzirinpu = 1512;
     public static final int gbgxsjxrvd = 397;
     public static final int ecsbytkmpp = 3963;
     public static final int mfkrksamrq = 4287;
     public static final int kghdsrgkmz = 9570;
     public static final int vljaepbsuq = 9033;
     public static final int jocfpulzka = 2482;
     public static final int rnnshzbkww = 2841;
     public static final int cvienfafpd = 1768;
     public static final int nlxvpuglfs = 7196;
     public static final int vevtcpdhel = 7949;
     public static final int iyzvgrhcsi = 570;
     public static final int qzxgetnjui = 6031;
     public static final int qlgivyrdih = 6525;
     public static final int tkalpjwhfq = 1081;
     public static final int bhpjftkfdh = 2536;
     public static final int kjpzmrgrkb = 2818;
     public static final int oofrgblljt = 8637;
     public static final int ntxmdstzba = 9234;
     public static final int utrpzuhozw = 6733;
     public static final int ltjmhkehxb = 5866;
     public static final int jftczfpdpc = 3200;
     public static final int muodigdnme = 741;
     public static final int hpdajhupqk = 796;
     public static final int djceldqopy = 5187;
     public static final int zevpnvxjvl = 7866;
     public static final int nzzlefvkns = 7264;
     public static final int wjrvhcever = 4026;
     public static final int njvdqspucu = 7754;
     public static final int thwntuklnt = 212;
     public static final int wlkprhyywc = 8464;
     public static final int bvuefocpvd = 3934;
     public static final int adnahyycdq = 8945;
     public static final int ailwjuxicx = 2395;
     public static final int ehtiaddpyl = 7603;
     public static final int qhddictomo = 3088;
     public static final int tcbsvcimxr = 8697;
     public static final int qcdaugxvhr = 3208;
     public static final int wyucwduwqg = 4755;
     public static final int jrosoepzuu = 4472;
     public static final int uzaeqoemzo = 366;
     public static final int rkclphuudp = 9834;
     public static final int plymodjiuv = 1028;
     public static final int gkuxsauste = 6202;
     public static final int onwaetpvrd = 524;
     public static final int rkzcugyryx = 673;
     public static final int booinccbst = 77;
     public static final int cnfpdmbvpw = 1103;
     public static final int vstvmohsou = 8944;
     public static final int vltwrogoyc = 783;
     public static final int qgustrybav = 4601;
     public static final int eghcztozkn = 530;
     public static final int nqxphxofay = 4907;
     public static final int xduifyvnfl = 5408;
     public static final int hkxejcyobh = 7007;
     public static final int svznnbjcma = 9492;
     public static final int ancwbsssey = 4942;
     public static final int tedtchdvev = 2762;
     public static final int qmqddjhzty = 7560;
     public static final int hwpqggwkpj = 2810;
     public static final int pcbbgecsow = 2830;
     public static final int yjcanwcdsk = 5575;
     public static final int fcajsmuhdj = 7716;
     public static final int dhmhnmvknu = 2523;
     public static final int tojufelbcy = 6790;
     public static final int dbcdecqyls = 7677;
     public static final int etcqrqplxl = 1410;
     public static final int hkqizaijbk = 5554;
     public static final int jxsknhizwh = 8314;
     public static final int hegeutguza = 8835;
     public static final int fibykjmwsi = 1968;
     public static final int wkvgujwmgi = 3113;
     public static final int iyghvuskze = 5038;
     public static final int jawfpzldhs = 2745;
     public static final int bwueidplag = 6851;
     public static final int zlqfhbgomw = 5549;
     public static final int jmdrrdscdf = 8517;
     public static final int xfcjmsfyxe = 7733;
     public static final int emxxoybele = 9927;
     public static final int bdnaympeho = 3230;
     public static final int nlktmeywwe = 2065;
     public static final int rlbgsqjgxl = 1773;
     public static final int bvzlxriytt = 2679;
     public static final int hwcactkpmz = 3131;
     public static final int tfzyrbcdnt = 5407;
     public static final int qretlesoyr = 7052;
     public static final int szrszcuiub = 5160;
     public static final int fybwjrrbim = 2958;
     public static final int gjawijfqnd = 5826;
     public static final int jyonmtadil = 4543;
     public static final int lgsaeihmwf = 9130;
     public static final int zgwwhwovzo = 5341;
     public static final int wyyqfopton = 6443;
     public static final int ajzydwfpkt = 3306;
     public static final int vveirxgmbz = 5047;
     public static final int hwczbbtrsw = 6553;
     public static final int owovpapycf = 6997;
     public static final int ybocdjlmaq = 4075;
     public static final int piylcpekcr = 6401;
     public static final int xgnlpqjmpa = 9484;
     public static final int psdudcxrxf = 9692;
     public static final int citoofmjzr = 8738;
     public static final int rbaildgnps = 7889;
     public static final int wnowmdatwc = 6034;
     public static final int umixwqonvo = 5196;
     public static final int nvpdctfpdh = 53;
     public static final int ipipmwfvvc = 9497;
     public static final int cwqahykphq = 7516;
     public static final int ilpngfokot = 584;
     public static final int egzwucwzoj = 685;
     public static final int tzaqqfgiei = 6331;
     public static final int lojytknnaw = 3205;
     public static final int dsglogyrwe = 8745;
     public static final int fnhjmdqusz = 5694;
     public static final int dautvairfd = 7762;
     public static final int jtvnthtzbn = 557;
     public static final int auqapgbxqo = 4398;
     public static final int dlzladqhvk = 9956;
     public static final int stuicfrvgj = 9611;
     public static final int erbjsutlip = 3508;
     public static final int uruhqzbxzf = 3921;
     public static final int xcyntenckh = 2331;
     public static final int fxpdtryfqw = 4391;
     public static final int xslmguymoc = 6440;
     public static final int kxlfomawyg = 2078;
     public static final int iklrtngpsv = 6440;
     public static final int pgichtpqwg = 7797;
     public static final int ofmembhsaa = 8718;
     public static final int mouiqkzwam = 7721;
     public static final int ofhjccciwt = 3976;
     public static final int onbwnmcnhl = 4498;
     public static final int muvsntqjyh = 3632;
     public static final int knregasfkv = 6248;
     public static final int zfpioszbvx = 8609;
     public static final int zkezknvuoc = 3769;
     public static final int qpdoxxoqct = 9485;
     public static final int faztjqahtt = 3560;
     public static final int qsyzzwapyv = 2369;
     public static final int xlpndtdvom = 5260;
     public static final int xwolajxkpn = 3860;
     public static final int nsnryzmrce = 6200;
     public static final int vphseihmvk = 1837;
     public static final int sqfynsbkks = 142;
     public static final int ybceilaxww = 862;
     public static final int vaeuhjtarj = 7769;
     public static final int ieybjssmmb = 3887;
     public static final int qomruyjonc = 497;
     public static final int zljcfrmslf = 6864;
     public static final int ixxekvdflk = 9810;
     public static final int bemcvtsyyq = 2452;
     public static final int ragdmpjoiw = 3400;
     public static final int eaoidnyxys = 8680;
     public static final int kvxxpbwtrj = 5506;
     public static final int shuxicnuil = 8966;
     public static final int fyfcbxxgcs = 2447;
     public static final int gsawydekii = 8351;
     public static final int jegqqddoxa = 3249;
     public static final int oljqcczlmd = 4571;
     public static final int kpcoljwabl = 6334;
     public static final int ahisrelukh = 873;
     public static final int fmetxehxqc = 9139;
     public static final int epfpdhfpfq = 4350;
     public static final int vtykipdjkf = 916;
     public static final int kcbxxasttn = 7544;
     public static final int hcjzpzwumg = 6806;
     public static final int uydvlkzepb = 4552;
     public static final int sqbdkennwx = 4234;
     public static final int dxifldmuef = 4166;
     public static final int owxztusztc = 4556;
     public static final int jfxywildbd = 1259;
     public static final int gzecsqpcuy = 5182;
     public static final int ascjaklhde = 321;
     public static final int echgzfauqj = 7898;
     public static final int hkhmloumrk = 5320;
     public static final int zckajyobav = 208;
     public static final int rqqmvgzxjh = 4947;
     public static final int tdxkdouyyx = 1491;
     public static final int zvonxomkkn = 640;
     public static final int ltjjwewani = 1958;
     public static final int zjowovjhzs = 107;
     public static final int dtqumocbys = 245;
     public static final int udmmrzonth = 5666;
     public static final int zoibhecnmr = 995;
     public static final int yqsnzrnpik = 4875;
     public static final int pojbzbpgcn = 8039;
     public static final int sxrcluvohc = 7870;
     public static final int xiicpvftot = 4105;
     public static final int javmcwonmh = 2510;
     public static final int zcfvoezgpf = 7165;
     public static final int lmajtzijtq = 9075;
     public static final int mzwzzwkphy = 5435;
     public static final int qbzuysoquv = 7433;
     public static final int iljhdgrpce = 3635;
     public static final int azkqzxjkdg = 6516;
     public static final int gkdoeggrsn = 5025;
     public static final int anjxtjbbgf = 8963;
     public static final int kaetakoggd = 1547;
     public static final int rxovyehiic = 3744;
     public static final int owqjrzvhze = 7871;
     public static final int zxoykyhpiv = 4054;
     public static final int fyopabcnhy = 2889;
     public static final int bsichegbry = 7244;
     public static final int fkyuojfikx = 9292;
     public static final int yjkclvvxsk = 5996;
     public static final int pfeovoyims = 969;
     public static final int gzoflljpra = 2814;
     public static final int awizuddpmf = 9;
     public static final int yzqnbbdzht = 9009;
     public static final int qufverbmhb = 5170;
     public static final int xqbzkuimce = 3941;
     public static final int futcvzjqdn = 241;
     public static final int jiqbytoinz = 5522;
     public static final int qvbvqhbeoq = 513;
     public static final int ycplssrzco = 6327;
     public static final int ppkagvihjf = 7860;
     public static final int ehvznfcdwm = 3457;
     public static final int rgqxacpdmk = 5775;
     public static final int gibydjohzv = 268;
     public static final int tsjyxsgifp = 1263;
     public static final int qyzcwrpzwa = 1624;
     public static final int mndqenlqxo = 2608;
     public static final int mymchafnyf = 9789;
     public static final int pgpajpowcn = 946;
     public static final int ovoadcynas = 1748;
     public static final int eroyumheby = 3431;
     public static final int xwfrpqmxvx = 4449;
     public static final int ifrxwjfspu = 7560;
     public static final int agyizlocuf = 8139;
     public static final int frurdrfhkd = 9254;
     public static final int vcooymbhkv = 1504;
     public static final int shqcwstcbp = 9689;
     public static final int uuxjxuqizf = 1960;
     public static final int jybvaoqnje = 4746;
     public static final int dcsiatdyry = 9583;
     public static final int nmzehfxhlz = 1451;
     public static final int rxrbbbuuhz = 3137;
     public static final int hozmttbblt = 5613;
     public static final int yqmdiheqri = 7054;
     public static final int uwacofzbda = 5270;
     public static final int dxqufhmbxh = 6545;
     public static final int rjjnouxhmx = 5017;
     public static final int dxyyvllaba = 7402;
     public static final int gcrxaoarfk = 5829;
     public static final int keqivfzdpg = 4740;
     public static final int bhskavtuco = 7126;
     public static final int mpbntenbhi = 9507;
     public static final int cgccptevid = 5882;
     public static final int egernfehiz = 8303;
     public static final int ivgywkrcls = 9375;
     public static final int readxotewh = 969;
     public static final int lhsqnpjatd = 5313;
     public static final int egqmmztjrw = 1162;
     public static final int unihabjpfe = 9924;
     public static final int sykrthdoap = 2033;
     public static final int wfyrkypdvh = 8269;
     public static final int ggkpoqsswr = 4522;
     public static final int dulyzlchyx = 4191;
     public static final int jzbvuygdkw = 3347;
     public static final int seofxletlr = 4949;
     public static final int nqpifinjrg = 8900;
     public static final int frdnxgzqhh = 1933;
     public static final int lxjbtkujso = 3339;
     public static final int mcpjwnjqfv = 8712;
     public static final int leuzsokkyj = 7772;
     public static final int emyhgbgkdi = 8494;
     public static final int drofiwbcaf = 7496;
     public static final int vwayiaeivy = 3810;
     public static final int ymitqeqzky = 6576;
     public static final int yyzrwegvdr = 6686;
     public static final int sazunenrrq = 9083;
     public static final int gdgdehqqrt = 8007;
     public static final int rndutuywrp = 592;
     public static final int vpezsvzdjw = 9787;
     public static final int vftrxsaeor = 8238;
     public static final int muucuyyube = 7314;
     public static final int anogvaykss = 9964;
     public static final int cnedlzrlip = 2278;
     public static final int bovcprxfay = 4694;
     public static final int mjgcowhljp = 2691;
     public static final int dficdearwz = 5638;
     public static final int ugucmqydxq = 5746;
     public static final int dzvmgsidzy = 1491;
     public static final int wkyttugdng = 2574;
     public static final int eeziojdecq = 1335;
     public static final int hfpsntrmmb = 8319;
     public static final int uzcvpzjdth = 2841;
     public static final int gvkhepsfrs = 5148;
     public static final int mrkopnpdsl = 2656;
     public static final int mdiewzzcdp = 7971;
     public static final int blmkvxxsyj = 9806;
     public static final int jvbznlbrfy = 9730;
     public static final int hzftarebtt = 4567;
     public static final int yjtmwmbsow = 4186;
     public static final int zocglgnbfm = 4699;
     public static final int yfnjwuamoe = 1853;
     public static final int calmruvity = 8189;
     public static final int asfchwgvsi = 3109;
     public static final int aqfkzuwazp = 2124;
     public static final int ozcbmqhdxh = 9235;
     public static final int airtptsgcv = 2858;
     public static final int bzwmnarzvo = 6241;
     public static final int poqmhxbdki = 76;
     public static final int tyjcfsmsag = 1224;
     public static final int iaooqwtnnm = 8680;
     public static final int ssrittnntn = 6379;
     public static final int slyotugsue = 1870;
     public static final int pggodxhunw = 6515;
     public static final int qxxhztdvdm = 7665;
     public static final int bmcfbcciff = 8403;
     public static final int vcstzgzmhf = 3124;
     public static final int avwdnfulyi = 4773;
     public static final int siwnrzjinw = 866;
     public static final int mewmhhvjfr = 59;
     public static final int jznibyijyh = 8139;
     public static final int hwrtppivbe = 2132;
     public static final int ewwhntbhod = 9661;
     public static final int kwlmishjpd = 9544;
     public static final int tgvzwoxxpp = 1541;
     public static final int kopanvsibe = 1165;
     public static final int wcuinuyngv = 679;
     public static final int cciieyfhfq = 6142;
     public static final int bvbdrkhplx = 7889;
     public static final int nvuwpmjxwz = 4500;
     public static final int kjcrhgiyjl = 7029;
     public static final int vpdldigqfl = 2494;
     public static final int jcmojaneiy = 3183;
     public static final int wljoimqeuo = 7221;
     public static final int hnibyhyksz = 2046;
     public static final int kzbwxbjwqt = 4554;
     public static final int zyxntzyhia = 4230;
     public static final int ycljdloewn = 5418;
     public static final int rrzltaxgtf = 8796;
     public static final int qmkvnhrvyw = 3032;
     public static final int tkybpwjwkh = 7386;
     public static final int dlysoifkrc = 7398;
     public static final int upvsgxkqiz = 6267;
     public static final int chhefoimfc = 4134;
     public static final int ogyuhjbtmh = 3441;
     public static final int kfvtrfsdsq = 9329;
     public static final int mutevkgknq = 2324;
     public static final int akwwxeebtu = 8450;
     public static final int xmegsjljvx = 9895;
     public static final int juqqeedtnv = 7916;
     public static final int wgeamzjawi = 4163;
     public static final int vigxdqoebz = 6716;
     public static final int dzdaqdqqjk = 2224;
     public static final int zhmuujwryu = 6272;
     public static final int cupdnlzwtc = 4439;
     public static final int kuiogoclwt = 3729;
     public static final int ktzjhwxixj = 5790;
     public static final int khohywuhgm = 5470;
     public static final int rjyoepwpjl = 9526;
     public static final int wiinnodwmb = 2679;
     public static final int ggtggvcdak = 8917;
     public static final int ixjswishwf = 2206;
     public static final int jcjsvkcyix = 2168;
     public static final int lvlgigqtky = 1532;
     public static final int hykaasrlik = 7379;
     public static final int rzevwyxyvg = 2933;
     public static final int jshavwobtg = 4866;
     public static final int bserskeynh = 6480;
     public static final int rorozpltrq = 4947;
     public static final int zgbufqrfnk = 3803;
     public static final int fgwhfhgnit = 5204;
     public static final int kxotdegswp = 7729;
     public static final int cyssjcxucz = 8329;
     public static final int eskeqqrrol = 769;
     public static final int wgkvpzzlll = 1159;
     public static final int aklilpbaeo = 7800;
     public static final int fcgdxsokkm = 5127;
     public static final int fysqpeeesl = 3064;
     public static final int nokjzesmzy = 5616;
     public static final int qnwpfqpzbc = 7268;
     public static final int xnvqrsdpkx = 1341;
     public static final int moyetnxmuh = 2683;
     public static final int nusfjhutoc = 3659;
     public static final int ajphhshkxj = 3244;
     public static final int yrdhblwpin = 3340;
     public static final int ieqsygbbjj = 4749;
     public static final int dipjzsvbpf = 9629;
     public static final int twdarlrfkk = 250;
     public static final int nlfzrwsivd = 5491;
     public static final int kdewzxbyfr = 2790;
     public static final int wxfniqlwwb = 667;
     public static final int hifderkvlz = 9757;
     public static final int sikugroett = 8586;
     public static final int amiyhnlmcu = 4753;
     public static final int kbpdxxqagy = 8889;
     public static final int otwphirtuc = 553;
     public static final int anlxvpmfly = 3359;
     public static final int nelnlmiqqk = 8884;
     public static final int cxhunlwpgo = 607;
     public static final int jpujjzjple = 5657;
     public static final int kdakgaydjd = 446;
     public static final int vsswcltmvl = 1241;
     public static final int nkpxirxpvw = 4685;
     public static final int lbemryowdz = 7101;
     public static final int eeahlwslqa = 146;
     public static final int cjstjxxgnx = 2695;
     public static final int xcizmcdkts = 5583;
     public static final int warcmbpcyv = 6141;
     public static final int yrttyahzga = 7613;
     public static final int fexvesikua = 1304;
     public static final int nbgdzdmbme = 3704;
     public static final int jbqohfyzob = 7422;
     public static final int fguimiyujm = 3409;
     public static final int gfmxsvamor = 1995;
     public static final int wqcatosnta = 535;
     public static final int elkjxpayfu = 3406;
     public static final int uifcpmmbud = 5642;
     public static final int nopqfdlfdl = 2365;
     public static final int gmciphslsj = 7176;
     public static final int bocrnenldg = 6907;
     public static final int fimsfjumhl = 6724;
     public static final int vzzzrytslm = 1365;
     public static final int eioiotowln = 3847;
     public static final int ltgaruicrg = 1236;
     public static final int cfznfxuauy = 4291;
     public static final int pafpnbdeff = 3883;
     public static final int dhnholosaj = 2458;
     public static final int ibjphdksvt = 3875;
     public static final int lrawolmjok = 1211;
     public static final int xlwbvgomkv = 6619;
     public static final int jfqilwsxvt = 8761;
     public static final int pwwaxxqghi = 4763;
     public static final int lpumunwaft = 9889;
     public static final int rfbldutkgi = 4328;
     public static final int kftvdwhpsy = 2009;
     public static final int nxogcsxcqf = 5603;
     public static final int azeaavbsnp = 8608;
     public static final int mfqpgvbqre = 8768;
     public static final int bboltvetwd = 7781;
     public static final int dibbvultxi = 5438;
     public static final int rsrrgkwsgr = 9016;
     public static final int lcpqkoewaw = 8520;
     public static final int spkkunhikv = 8304;
     public static final int qnjcigzppk = 1985;
     public static final int kfmdmuhdnh = 8014;
     public static final int qytihacspp = 9101;
     public static final int hsuhyuhzog = 2995;
     public static final int nnxtwtxckm = 6728;
     public static final int xgdhppndxy = 3563;
     public static final int uqsftnijxa = 2841;
     public static final int ninlrgjkej = 7127;
     public static final int tjtsqquega = 5828;
     public static final int oxogibiecl = 8002;
     public static final int dqnezbkeqa = 7648;
     public static final int zqevqevbmf = 9489;
     public static final int gjmaumyppn = 1314;
     public static final int oiwjkmfimh = 873;
     public static final int fkbcnhibsx = 6935;
     public static final int emgqzutnhn = 7547;
     public static final int vdxrsfktjk = 6677;
     public static final int tbojhwxsqw = 8589;
     public static final int vyeefnlywb = 4746;
     public static final int ccmeyoxzuw = 7579;
     public static final int jimknplsyl = 804;
     public static final int levkdljugn = 4613;
     public static final int clybakbnjb = 3442;
     public static final int ibcjsergcn = 9535;
     public static final int jvvfqdhlsq = 2302;
     public static final int sknxhpathn = 8435;
     public static final int wmpgsekyqb = 598;
     public static final int xavffvefni = 8080;
     public static final int oykakzcdxq = 4515;
     public static final int byuaueycit = 191;
     public static final int qbxbjxkrti = 5770;
     public static final int jusknhldbt = 3170;
     public static final int ctqjmbxtkq = 1998;
     public static final int skwtndqrst = 2776;
     public static final int zdraacsfqq = 2552;
     public static final int itoqyggacw = 8919;
     public static final int vdoemrdcel = 3159;
     public static final int zjtyonbdlr = 9308;
     public static final int agsaucekzz = 1066;
     public static final int zhlkzrouwf = 6743;
     public static final int lljelxacgp = 8425;
     public static final int xrzstolkjy = 6775;
     public static final int rxuvueuayb = 1564;
     public static final int gzxpduhtog = 8797;
     public static final int nufelfieov = 3172;
     public static final int rkfjductis = 7558;
     public static final int isganzcryt = 9839;
     public static final int spsctvxubx = 5357;
     public static final int zgjlecukbi = 1699;
     public static final int yvhidkwurv = 9890;
     public static final int dpvopdwjqx = 2443;
     public static final int pwjwzpqjuw = 8982;
     public static final int jnncpsqfkg = 2739;
     public static final int fzlfevaygg = 12;
     public static final int wkufhndjhn = 9019;
     public static final int jbmorkqjno = 1251;


}