// Date: 14.09.2015 19:47:47
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.hbm.render;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelGoggles extends ModelBiped
{
  public ModelGoggles()
  {
    textureWidth = 64;
    textureHeight = 32;
      
      bipedHead = new ModelRenderer(this, 0, 0);
      bipedHead.addBox(-4.5F, -3F - 2, -4.5F, 9, 3, 1);

      bipedHead.setTextureOffset(0, 4);
      bipedHead.addBox(-4.5F, -3F - 2, -3.5F, 9, 2, 5);

      bipedHead.setTextureOffset(26, 0);
      bipedHead.addBox(1F, -2.5F - 2, -5F, 2, 2, 1);

      bipedHead.setTextureOffset(20, 0);
      bipedHead.addBox(-3F, -2.5F - 2, -5F, 2, 2, 1);

      bipedHead.setTextureOffset(0, 11);
      bipedHead.addBox(-4.5F, -3F - 2, 0.5F, 9, 1, 4);
  }
  
  /*public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
  }*/
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  @Override
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    this.bipedHead.rotationPointX = 0.0F;
    this.bipedHead.rotationPointY = 0.0F;
    this.bipedHead.rotateAngleY = this.bipedHead.rotateAngleY;
    this.bipedHead.rotateAngleX = this.bipedHead.rotateAngleX;
  }
  @Override
public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
  {
	setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
    GL11.glPushMatrix();
    bipedHead.render(par7);
    GL11.glPopMatrix();
  }

}
