// Date: 19.05.2015 21:27:25
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.hbm.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBigSword extends ModelBase {

	ModelRenderer HandleBottom;
	ModelRenderer HandleGrip;
	ModelRenderer Handle1;
	ModelRenderer Handle2;
	ModelRenderer Blade;
	ModelRenderer SBladeTip;

	public ModelBigSword() {
		this.textureWidth = 128;
		this.textureHeight = 32;

		this.HandleBottom = new ModelRenderer(this, 1, 1);
		this.HandleBottom.addBox(0F, 0F, 0F, 1, 3, 3);
		this.HandleBottom.setRotationPoint(0F, 0F, 0F);
		this.HandleBottom.setTextureSize(64, 32);
		this.HandleBottom.mirror = true;
		setRotation(this.HandleBottom, -0.7853982F, 0F, 0F);
		this.HandleGrip = new ModelRenderer(this, 17, 1);
		this.HandleGrip.addBox(0F, 0F, 0F, 1, 5, 2);
		this.HandleGrip.setRotationPoint(0F, -4F, -1F);
		this.HandleGrip.setTextureSize(64, 32);
		this.HandleGrip.mirror = true;
		setRotation(this.HandleGrip, 0F, 0F, 0F);
		this.Handle1 = new ModelRenderer(this, 25, 1);
		this.Handle1.addBox(0F, -1F, 0F, 2, 1, 4);
		this.Handle1.setRotationPoint(-0.5F, -3F, 0F);
		this.Handle1.setTextureSize(64, 32);
		this.Handle1.mirror = true;
		setRotation(this.Handle1, 0.2617994F, 0F, 0F);
		this.Handle2 = new ModelRenderer(this, 41, 1);
		this.Handle2.addBox(0F, -1F, -4F, 2, 1, 4);
		this.Handle2.setRotationPoint(-0.5F, -3F, 0F);
		this.Handle2.setTextureSize(64, 32);
		this.Handle2.mirror = true;
		setRotation(this.Handle2, -0.2617994F, 0F, 0F);
		this.Blade = new ModelRenderer(this, 57, 1);
		this.Blade.addBox(0F, 0F, 0F, 3, 18, 1);
		this.Blade.setRotationPoint(0F, -22F, 1.5F);
		this.Blade.setTextureSize(64, 32);
		this.Blade.mirror = true;
		setRotation(this.Blade, 0F, 1.570796F, 0F);
		this.SBladeTip = new ModelRenderer(this, 2, 10);
		this.SBladeTip.addBox(0F, 0F, 0F, 1, 2, 2);
		this.SBladeTip.setRotationPoint(0F, -23.5F, 0F);
		this.SBladeTip.setTextureSize(64, 32);
		this.SBladeTip.mirror = true;
		setRotation(this.SBladeTip, -0.7853982F, 0F, 0F);
	}

	@Override
	public void render(Entity entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scaleFactor) {

		this.HandleBottom.render(scaleFactor);
		this.HandleGrip.render(scaleFactor);
		this.Handle1.render(scaleFactor);
		this.Handle2.render(scaleFactor);
		this.Blade.render(scaleFactor);
		this.SBladeTip.render(scaleFactor);
	}

	private static void setRotation(ModelRenderer model, float x, float y, float z) {

		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}
