// Date: 07.01.2016 13:25:20
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.hbm.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelStatue extends ModelBase {

	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Shape3;
	ModelRenderer Shape4;
	ModelRenderer Shape6;
	ModelRenderer Shape7;
	ModelRenderer Shape8;
	ModelRenderer Shape9;
	ModelRenderer Shape10;

	public ModelStatue() {
		this.textureWidth = 64;
		this.textureHeight = 64;

		this.Shape1 = new ModelRenderer(this, 0, 0);
		this.Shape1.addBox(0F, 0F, 0F, 16, 8, 16);
		this.Shape1.setRotationPoint(-8F, 16F, -8F);
		this.Shape1.setTextureSize(64, 64);
		this.Shape1.mirror = true;
		setRotation(this.Shape1, 0F, 0F, 0F);
		this.Shape2 = new ModelRenderer(this, 0, 24);
		this.Shape2.addBox(0F, 0F, 0F, 4, 12, 4);
		this.Shape2.setRotationPoint(-4F, 4F, -2F);
		this.Shape2.setTextureSize(64, 64);
		this.Shape2.mirror = true;
		setRotation(this.Shape2, 0F, 0F, 0F);
		this.Shape3 = new ModelRenderer(this, 16, 24);
		this.Shape3.addBox(0F, 0F, 0F, 4, 12, 4);
		this.Shape3.setRotationPoint(0F, 4F, -2F);
		this.Shape3.setTextureSize(64, 64);
		this.Shape3.mirror = true;
		setRotation(this.Shape3, 0F, 0F, 0F);
		this.Shape4 = new ModelRenderer(this, 32, 40);
		this.Shape4.addBox(0F, 0F, 0F, 8, 12, 4);
		this.Shape4.setRotationPoint(-4F, -8F, -2F);
		this.Shape4.setTextureSize(64, 64);
		this.Shape4.mirror = true;
		setRotation(this.Shape4, 0F, 0F, 0F);
		this.Shape6 = new ModelRenderer(this, 0, 40);
		this.Shape6.addBox(0F, 0F, -2F, 4, 8, 4);
		this.Shape6.setRotationPoint(4F, -8F, 0F);
		this.Shape6.setTextureSize(64, 64);
		this.Shape6.mirror = true;
		setRotation(this.Shape6, 0.5235988F, 0F, 0F);
		this.Shape7 = new ModelRenderer(this, 16, 40);
		this.Shape7.addBox(-4F, 0F, -2F, 4, 8, 4);
		this.Shape7.setRotationPoint(-4F, -8F, 0F);
		this.Shape7.setTextureSize(64, 64);
		this.Shape7.mirror = true;
		setRotation(this.Shape7, -0.0872665F, 0F, 0F);
		this.Shape8 = new ModelRenderer(this, 0, 52);
		this.Shape8.addBox(-2F, 0F, -2F, 4, 8, 4);
		this.Shape8.setRotationPoint(6F, -2F, 3F);
		this.Shape8.setTextureSize(64, 64);
		this.Shape8.mirror = true;
		setRotation(this.Shape8, 1.22173F, 0F, 0F);
		this.Shape9 = new ModelRenderer(this, 16, 52);
		this.Shape9.addBox(0F, 0F, -2F, 4, 8, 4);
		this.Shape9.setRotationPoint(-8F, -1F, -0.5F);
		this.Shape9.setTextureSize(64, 64);
		this.Shape9.mirror = true;
		setRotation(this.Shape9, 0.2617994F, 0F, 0F);
		this.Shape10 = new ModelRenderer(this, 32, 24);
		this.Shape10.addBox(-4F, -8F, -4F, 8, 8, 8);
		this.Shape10.setRotationPoint(0F, -8F, 0F);
		this.Shape10.setTextureSize(64, 64);
		this.Shape10.mirror = true;
		setRotation(this.Shape10, -0.1745329F, 0F, 0F);
	}

	@Override
	public void render(Entity entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scaleFactor) {

		this.renderModel(scaleFactor);
	}

	public void renderModel(float scaleFactor) {

		this.Shape1.render(scaleFactor);
		this.Shape2.render(scaleFactor);
		this.Shape3.render(scaleFactor);
		this.Shape4.render(scaleFactor);
		this.Shape6.render(scaleFactor);
		this.Shape7.render(scaleFactor);
		this.Shape8.render(scaleFactor);
		this.Shape9.render(scaleFactor);
		this.Shape10.render(scaleFactor);
	}

	private static void setRotation(ModelRenderer model, float x, float y, float z) {

		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}
