// Date: 28.11.2018 08:36:32
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.hbm.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelGeiger extends ModelBase {

	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Shape3;
	ModelRenderer Shape4;
	ModelRenderer Shape5;
	ModelRenderer Shape6;
	ModelRenderer Shape7;
	ModelRenderer Shape8;

	public ModelGeiger() {
		this.textureWidth = 64;
		this.textureHeight = 32;

		this.Shape1 = new ModelRenderer(this, 0, 0);
		this.Shape1.addBox(0F, 0F, 0F, 12, 7, 5);
		this.Shape1.setRotationPoint(-5F, 17F, 1F);
		this.Shape1.setTextureSize(64, 32);
		this.Shape1.mirror = true;
		setRotation(this.Shape1, 0F, 0F, 0F);
		this.Shape2 = new ModelRenderer(this, 0, 30);
		this.Shape2.addBox(0F, 0F, 0F, 7, 1, 1);
		this.Shape2.setRotationPoint(-2.5F, 15F, 3F);
		this.Shape2.setTextureSize(64, 32);
		this.Shape2.mirror = true;
		setRotation(this.Shape2, 0F, 0F, 0F);
		this.Shape3 = new ModelRenderer(this, 10, 18);
		this.Shape3.addBox(0F, 0F, 0F, 1, 2, 1);
		this.Shape3.setRotationPoint(-3F, 15.5F, 3F);
		this.Shape3.setTextureSize(64, 32);
		this.Shape3.mirror = true;
		setRotation(this.Shape3, 0F, 0F, 0F);
		this.Shape4 = new ModelRenderer(this, 14, 18);
		this.Shape4.addBox(0F, 0F, 0F, 1, 2, 1);
		this.Shape4.setRotationPoint(4F, 15.5F, 3F);
		this.Shape4.setTextureSize(64, 32);
		this.Shape4.mirror = true;
		setRotation(this.Shape4, 0F, 0F, 0F);
		this.Shape5 = new ModelRenderer(this, 0, 12);
		this.Shape5.addBox(0F, 0F, 0F, 7, 3, 3);
		this.Shape5.setRotationPoint(-4F, 21F, -6F);
		this.Shape5.setTextureSize(64, 32);
		this.Shape5.mirror = true;
		setRotation(this.Shape5, 0F, 0F, 0F);
		this.Shape6 = new ModelRenderer(this, 20, 12);
		this.Shape6.addBox(0F, 0F, 0F, 2, 6, 2);
		this.Shape6.setRotationPoint(-7F, 18F, 2.5F);
		this.Shape6.setTextureSize(64, 32);
		this.Shape6.mirror = true;
		setRotation(this.Shape6, 0F, 0F, 0F);
		this.Shape7 = new ModelRenderer(this, 0, 18);
		this.Shape7.addBox(0F, 0F, 0F, 3, 2, 2);
		this.Shape7.setRotationPoint(-7F, 22F, -5.5F);
		this.Shape7.setTextureSize(64, 32);
		this.Shape7.mirror = true;
		setRotation(this.Shape7, 0F, 0F, 0F);
		this.Shape8 = new ModelRenderer(this, 0, 22);
		this.Shape8.addBox(0F, 0F, 0F, 2, 2, 6);
		this.Shape8.setRotationPoint(-7F, 22F, -3.5F);
		this.Shape8.setTextureSize(64, 32);
		this.Shape8.mirror = true;
		setRotation(this.Shape8, 0F, 0F, 0F);
	}

	@Override
	public void render(Entity entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scaleFactor) {

		this.renderModel(scaleFactor);
	}

	public void renderModel(float scaleFactor) {

		this.Shape1.render(scaleFactor);
		this.Shape2.render(scaleFactor);
		this.Shape3.render(scaleFactor);
		this.Shape4.render(scaleFactor);
		this.Shape5.render(scaleFactor);
		this.Shape6.render(scaleFactor);
		this.Shape7.render(scaleFactor);
		this.Shape8.render(scaleFactor);
	}

	private static void setRotation(ModelRenderer model, float x, float y, float z) {

		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}
