// Date: 19.05.2015 14:19:31
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.hbm.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSword extends ModelBase {

	ModelRenderer GripBottom;
	ModelRenderer GripHandle;
	ModelRenderer Shield;
	ModelRenderer Blade;
	ModelRenderer BladeTip;
	ModelRenderer Shield1;
	ModelRenderer Shield2;

	public ModelSword() {
		this.textureWidth = 64;
		this.textureHeight = 32;

		this.GripBottom = new ModelRenderer(this, 0, 17);
		this.GripBottom.addBox(0F, 0F, 0F, 3, 3, 1);
		this.GripBottom.setRotationPoint(0F, 0F, 0F);
		this.GripBottom.setTextureSize(64, 32);
		this.GripBottom.mirror = true;
		setRotation(this.GripBottom, 0F, 0F, 0F);
		this.GripHandle = new ModelRenderer(this, 8, 2);
		this.GripHandle.addBox(0F, 0F, 0F, 2, 5, 1);
		this.GripHandle.setRotationPoint(0.5F, -5F, 0F);
		this.GripHandle.setTextureSize(64, 32);
		this.GripHandle.mirror = true;
		setRotation(this.GripHandle, 0F, 0F, 0F);
		this.Shield = new ModelRenderer(this, 14, 5);
		this.Shield.addBox(0F, 0F, 0F, 6, 1, 3);
		this.Shield.setRotationPoint(-1.5F, -6F, -1F);
		this.Shield.setTextureSize(64, 32);
		this.Shield.mirror = true;
		setRotation(this.Shield, 0F, 0F, 0F);
		this.Blade = new ModelRenderer(this, 0, 0);
		this.Blade.addBox(0F, 0F, 0F, 3, 16, 1);
		this.Blade.setRotationPoint(0F, -22F, 0F);
		this.Blade.setTextureSize(64, 32);
		this.Blade.mirror = true;
		setRotation(this.Blade, 0F, 0F, 0F);
		this.BladeTip = new ModelRenderer(this, 8, 0);
		this.BladeTip.addBox(0F, 0F, 0F, 2, 1, 1);
		this.BladeTip.setRotationPoint(0.5F, -23F, 0F);
		this.BladeTip.setTextureSize(64, 32);
		this.BladeTip.mirror = true;
		setRotation(this.BladeTip, 0F, 0F, 0F);
		this.Shield1 = new ModelRenderer(this, 14, 0);
		this.Shield1.addBox(0F, 0F, 0F, 1, 1, 4);
		this.Shield1.setRotationPoint(-2F, -6.5F, -1.5F);
		this.Shield1.setTextureSize(64, 32);
		this.Shield1.mirror = true;
		setRotation(this.Shield1, 0F, 0F, 0F);
		this.Shield2 = new ModelRenderer(this, 24, 0);
		this.Shield2.addBox(0F, 0F, 0F, 1, 1, 4);
		this.Shield2.setRotationPoint(4F, -6.5F, -1.5F);
		this.Shield2.setTextureSize(64, 32);
		this.Shield2.mirror = true;
		setRotation(this.Shield2, 0F, 0F, 0F);
	}

	@Override
	public void render(Entity entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scaleFactor) {

		this.GripBottom.render(scaleFactor);
		this.GripHandle.render(scaleFactor);
		this.Shield.render(scaleFactor);
		this.Blade.render(scaleFactor);
		this.BladeTip.render(scaleFactor);
		this.Shield1.render(scaleFactor);
		this.Shield2.render(scaleFactor);
	}

	private static void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}
