// Date: 11.02.2017 13:00:27
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.hbm.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelRubble extends ModelBase {

	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Shape3;
	ModelRenderer Shape4;
	ModelRenderer Shape5;
	ModelRenderer Shape6;
	ModelRenderer Shape7;
	ModelRenderer Shape8;
	ModelRenderer Shape9;
	ModelRenderer Shape10;

	public ModelRubble() {
		this.textureWidth = 16;
		this.textureHeight = 16;

		this.Shape1 = new ModelRenderer(this, 0, 0);
		this.Shape1.addBox(0F, 0F, 0F, 14, 6, 6);
		this.Shape1.setRotationPoint(-7F, 1F, 2F);
		this.Shape1.setTextureSize(64, 32);
		this.Shape1.mirror = true;
		setRotation(this.Shape1, 0F, 0F, 0F);
		this.Shape2 = new ModelRenderer(this, 0, 0);
		this.Shape2.addBox(0F, 0F, 0F, 6, 13, 5);
		this.Shape2.setRotationPoint(-7F, -6F, -5F);
		this.Shape2.setTextureSize(64, 32);
		this.Shape2.mirror = true;
		setRotation(this.Shape2, 0F, 0F, 0F);
		this.Shape3 = new ModelRenderer(this, 0, 0);
		this.Shape3.addBox(0F, 0F, 0F, 6, 6, 6);
		this.Shape3.setRotationPoint(1F, 1F, -5F);
		this.Shape3.setTextureSize(64, 32);
		this.Shape3.mirror = true;
		setRotation(this.Shape3, 0F, 0F, 0F);
		this.Shape4 = new ModelRenderer(this, 0, 0);
		this.Shape4.addBox(0F, 0F, 0F, 14, 7, 4);
		this.Shape4.setRotationPoint(-7F, -7F, 2F);
		this.Shape4.setTextureSize(64, 32);
		this.Shape4.mirror = true;
		setRotation(this.Shape4, 0F, 0.4363323F, 0F);
		this.Shape5 = new ModelRenderer(this, 0, 0);
		this.Shape5.addBox(0F, 0F, 0F, 6, 6, 11);
		this.Shape5.setRotationPoint(0F, -6F, -5F);
		this.Shape5.setTextureSize(64, 32);
		this.Shape5.mirror = true;
		setRotation(this.Shape5, 0F, 0F, 0F);
		this.Shape6 = new ModelRenderer(this, 0, 0);
		this.Shape6.addBox(0F, 0F, 0F, 8, 8, 8);
		this.Shape6.setRotationPoint(-4F, -4F, -4F);
		this.Shape6.setTextureSize(64, 32);
		this.Shape6.mirror = true;
		setRotation(this.Shape6, 0F, 0F, 0F);
		this.Shape7 = new ModelRenderer(this, 0, 0);
		this.Shape7.addBox(0F, 0F, 0F, 6, 5, 7);
		this.Shape7.setRotationPoint(-7F, -5F, 1F);
		this.Shape7.setTextureSize(64, 32);
		this.Shape7.mirror = true;
		setRotation(this.Shape7, 0F, 0F, 0F);
		this.Shape8 = new ModelRenderer(this, 0, 0);
		this.Shape8.addBox(0F, 0F, 0F, 12, 6, 4);
		this.Shape8.setRotationPoint(-6F, -1F, 3F);
		this.Shape8.setTextureSize(64, 32);
		this.Shape8.mirror = true;
		setRotation(this.Shape8, 0F, 0F, -0.3490659F);
		this.Shape9 = new ModelRenderer(this, 0, 0);
		this.Shape9.addBox(0F, 0F, 0F, 12, 6, 6);
		this.Shape9.setRotationPoint(-6F, 2F, -3F);
		this.Shape9.setTextureSize(64, 32);
		this.Shape9.mirror = true;
		setRotation(this.Shape9, 0F, -0.2094395F, 0F);
		this.Shape10 = new ModelRenderer(this, 0, 0);
		this.Shape10.addBox(0F, 0F, 0F, 6, 10, 4);
		this.Shape10.setRotationPoint(-5F, -3F, -6F);
		this.Shape10.setTextureSize(64, 32);
		this.Shape10.mirror = true;
		setRotation(this.Shape10, 0F, 0F, -0.3490659F);
	}

	@Override
	public void render(Entity entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scaleFactor) {

		this.renderAll(scaleFactor);
	}

	public void renderAll(float scaleFactor) {

		this.Shape1.render(scaleFactor);
		this.Shape2.render(scaleFactor);
		this.Shape3.render(scaleFactor);
		this.Shape4.render(scaleFactor);
		this.Shape5.render(scaleFactor);
		this.Shape6.render(scaleFactor);
		this.Shape7.render(scaleFactor);
		this.Shape8.render(scaleFactor);
		this.Shape9.render(scaleFactor);
		this.Shape10.render(scaleFactor);
	}

	private static void setRotation(ModelRenderer model, float x, float y, float z) {

		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}
