// Date: 04.10.2015 21:16:44
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.hbm.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPoleTop extends ModelBase {

	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Shape3;
	ModelRenderer Shape4;
	ModelRenderer Shape5;
	ModelRenderer Shape6;

	public ModelPoleTop() {
		this.textureWidth = 64;
		this.textureHeight = 64;

		this.Shape1 = new ModelRenderer(this, 0, 1);
		this.Shape1.addBox(0F, 0F, 0F, 12, 8, 12);
		this.Shape1.setRotationPoint(-6F, 16F, -6F);
		this.Shape1.setTextureSize(64, 64);
		this.Shape1.mirror = true;
		setRotation(this.Shape1, 0F, 0F, 0F);
		this.Shape2 = new ModelRenderer(this, 0, 23);
		this.Shape2.addBox(0F, 0F, 0F, 4, 16, 4);
		this.Shape2.setRotationPoint(4F, 4F, -8F);
		this.Shape2.setTextureSize(64, 64);
		this.Shape2.mirror = true;
		setRotation(this.Shape2, 0F, 0F, 0F);
		this.Shape3 = new ModelRenderer(this, 0, 23);
		this.Shape3.addBox(0F, 0F, 0F, 4, 16, 4);
		this.Shape3.setRotationPoint(4F, 4F, 4F);
		this.Shape3.setTextureSize(64, 64);
		this.Shape3.mirror = true;
		setRotation(this.Shape3, 0F, 0F, 0F);
		this.Shape4 = new ModelRenderer(this, 0, 23);
		this.Shape4.addBox(0F, 0F, 0F, 4, 16, 4);
		this.Shape4.setRotationPoint(-8F, 4F, -8F);
		this.Shape4.setTextureSize(64, 64);
		this.Shape4.mirror = true;
		setRotation(this.Shape4, 0F, 0F, 0F);
		this.Shape5 = new ModelRenderer(this, 0, 23);
		this.Shape5.addBox(0F, 0F, 0F, 4, 16, 4);
		this.Shape5.setRotationPoint(-8F, 4F, 4F);
		this.Shape5.setTextureSize(64, 64);
		this.Shape5.mirror = true;
		setRotation(this.Shape5, 0F, 0F, 0F);
		this.Shape6 = new ModelRenderer(this, 0, 47);
		this.Shape6.addBox(0F, 0F, 0F, 4, 2, 4);
		this.Shape6.setRotationPoint(-2F, 14F, -2F);
		this.Shape6.setTextureSize(64, 64);
		this.Shape6.mirror = true;
		setRotation(this.Shape6, 0F, 0F, 0F);
	}

	@Override
	public void render(Entity entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scaleFactor) {

		this.renderModel(scaleFactor);
	}

	public void renderModel(float scaleFactor) {
		this.Shape1.render(scaleFactor);
		this.Shape2.render(scaleFactor);
		this.Shape3.render(scaleFactor);
		this.Shape4.render(scaleFactor);
		this.Shape5.render(scaleFactor);
		this.Shape6.render(scaleFactor);
	}

	private static void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}
