// Date: 04.10.2015 22:20:45
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.hbm.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSatelliteReceiver extends ModelBase {

	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Shape3;
	ModelRenderer Shape4;
	ModelRenderer Shape5;
	ModelRenderer Shape6;
	ModelRenderer Shape7;
	ModelRenderer Shape8;
	ModelRenderer Shape9;

	public ModelSatelliteReceiver() {
		this.textureWidth = 64;
		this.textureHeight = 64;

		this.Shape1 = new ModelRenderer(this, 0, 0);
		this.Shape1.addBox(0F, 0F, 0F, 12, 16, 12);
		this.Shape1.setRotationPoint(-6F, 8F, -6F);
		this.Shape1.setTextureSize(64, 64);
		this.Shape1.mirror = true;
		setRotation(this.Shape1, 0F, 0F, 0F);
		this.Shape2 = new ModelRenderer(this, 10, 28);
		this.Shape2.addBox(3F, 9F, -8F, 8, 8, 2);
		this.Shape2.setRotationPoint(-3F, 6F, 0F);
		this.Shape2.setTextureSize(64, 64);
		this.Shape2.mirror = true;
		setRotation(this.Shape2, -0.2617994F, -0.4363323F, 0F);
		this.Shape3 = new ModelRenderer(this, 0, 39);
		this.Shape3.addBox(3F, 7F, -10F, 8, 2, 3);
		this.Shape3.setRotationPoint(-3F, 6F, 0F);
		this.Shape3.setTextureSize(64, 64);
		this.Shape3.mirror = true;
		setRotation(this.Shape3, -0.2617994F, -0.4363323F, 0F);
		this.Shape4 = new ModelRenderer(this, 0, 28);
		this.Shape4.addBox(1F, 9F, -10F, 2, 8, 3);
		this.Shape4.setRotationPoint(-3F, 6F, 0F);
		this.Shape4.setTextureSize(64, 64);
		this.Shape4.mirror = true;
		setRotation(this.Shape4, -0.2617994F, -0.4363323F, 0F);
		this.Shape5 = new ModelRenderer(this, 0, 28);
		this.Shape5.addBox(11F, 9F, -10F, 2, 8, 3);
		this.Shape5.setRotationPoint(-3F, 6F, 0F);
		this.Shape5.setTextureSize(64, 64);
		this.Shape5.mirror = true;
		setRotation(this.Shape5, -0.2617994F, -0.4363323F, 0F);
		this.Shape6 = new ModelRenderer(this, 0, 39);
		this.Shape6.addBox(3F, 17F, -10F, 8, 2, 3);
		this.Shape6.setRotationPoint(-3F, 6F, 0F);
		this.Shape6.setTextureSize(64, 64);
		this.Shape6.mirror = true;
		setRotation(this.Shape6, -0.2617994F, -0.4363323F, 0F);
		this.Shape7 = new ModelRenderer(this, 0, 44);
		this.Shape7.addBox(6F, 12F, -11F, 2, 2, 3);
		this.Shape7.setRotationPoint(-3F, 6F, 0F);
		this.Shape7.setTextureSize(64, 64);
		this.Shape7.mirror = true;
		setRotation(this.Shape7, -0.2617994F, -0.4363323F, 0F);
		this.Shape8 = new ModelRenderer(this, 0, 49);
		this.Shape8.addBox(6.5F, 12.5F, -14F, 1, 1, 3);
		this.Shape8.setRotationPoint(-3F, 6F, 0F);
		this.Shape8.setTextureSize(64, 64);
		this.Shape8.mirror = true;
		setRotation(this.Shape8, -0.2617994F, -0.4363323F, 0F);
		this.Shape9 = new ModelRenderer(this, 0, 53);
		this.Shape9.addBox(6F, 12F, -16F, 2, 2, 2);
		this.Shape9.setRotationPoint(-3F, 6F, 0F);
		this.Shape9.setTextureSize(64, 64);
		this.Shape9.mirror = true;
		setRotation(this.Shape9, -0.2617994F, -0.4363323F, 0F);
	}

	@Override
	public void render(Entity entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scaleFactor) {

		this.renderModel(scaleFactor);
	}

	public void renderModel(float scaleFactor) {

		this.Shape1.render(scaleFactor);
		this.Shape2.render(scaleFactor);
		this.Shape3.render(scaleFactor);
		this.Shape4.render(scaleFactor);
		this.Shape5.render(scaleFactor);
		this.Shape6.render(scaleFactor);
		this.Shape7.render(scaleFactor);
		this.Shape8.render(scaleFactor);
		this.Shape9.render(scaleFactor);
	}

	private static void setRotation(ModelRenderer model, float x, float y, float z) {

		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}
