// Date: 23.07.2016 18:06:22
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.hbm.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ProtoCopter extends ModelBase {

	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Shape3;
	ModelRenderer Shape4;
	ModelRenderer Shape5;
	ModelRenderer Shape6;
	ModelRenderer Shape7;
	ModelRenderer Shape8;

	public ProtoCopter() {
		this.textureWidth = 128;
		this.textureHeight = 64;

		int x = 0;
		int z = -2;

		this.Shape1 = new ModelRenderer(this, 0, 0);
		this.Shape1.addBox(0F, 0F, 0F, 16, 4, 4);
		this.Shape1.setRotationPoint(-8F + x, 0F, 0F + z);
		this.Shape1.setTextureSize(128, 64);
		this.Shape1.mirror = true;
		setRotation(this.Shape1, 0F, 0F, 0F);
		this.Shape2 = new ModelRenderer(this, 0, 0);
		this.Shape2.addBox(0F, 0F, 0F, 4, 8, 4);
		this.Shape2.setRotationPoint(-12F + x, 0F, 0F + z);
		this.Shape2.setTextureSize(128, 64);
		this.Shape2.mirror = true;
		setRotation(this.Shape2, 0F, 0F, 0F);
		this.Shape3 = new ModelRenderer(this, 0, 0);
		this.Shape3.addBox(0F, 0F, 0F, 7, 3, 2);
		this.Shape3.setRotationPoint(8F + x, 0F, 1F + z);
		this.Shape3.setTextureSize(128, 64);
		this.Shape3.mirror = true;
		setRotation(this.Shape3, 0F, 0F, 0F);
		this.Shape4 = new ModelRenderer(this, 0, 0);
		this.Shape4.addBox(0F, 0F, 0F, 6, 6, 2);
		this.Shape4.setRotationPoint(15F + x, 0F, 1F + z);
		this.Shape4.setTextureSize(128, 64);
		this.Shape4.mirror = true;
		setRotation(this.Shape4, 0F, 0F, 0F);
		this.Shape5 = new ModelRenderer(this, 0, 0);
		this.Shape5.addBox(0F, 0F, 0F, 5, 5, 2);
		this.Shape5.setRotationPoint(-8F + x, 3F, 1F + z);
		this.Shape5.setTextureSize(128, 64);
		this.Shape5.mirror = true;
		setRotation(this.Shape5, 0F, 0F, 0F);
		this.Shape6 = new ModelRenderer(this, 0, 0);
		this.Shape6.addBox(0F, 0F, 0F, 4, 2, 14);
		this.Shape6.setRotationPoint(-3F + x, 4F, -5F + z);
		this.Shape6.setTextureSize(128, 64);
		this.Shape6.mirror = true;
		setRotation(this.Shape6, 0F, 0F, 0F);
		this.Shape7 = new ModelRenderer(this, 0, 0);
		this.Shape7.addBox(0F, 0F, 0F, 2, 4, 2);
		this.Shape7.setRotationPoint(-1F + x, -4F, 1F + z);
		this.Shape7.setTextureSize(128, 64);
		this.Shape7.mirror = true;
		setRotation(this.Shape7, 0F, 0F, 0F);
		this.Shape8 = new ModelRenderer(this, 0, 0);
		this.Shape8.addBox(-14F, 0F, -14F, 28, 1, 28);
		this.Shape8.setRotationPoint(0F + x, -3F, 2F + z);
		this.Shape8.setTextureSize(128, 64);
		this.Shape8.mirror = true;
		setRotation(this.Shape8, 0F, 0F, 0F);
	}

	@Override
	public void render(Entity entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scaleFactor) {

		this.renderAll(scaleFactor);
	}

	public void renderAll(float f5) {

		this.Shape1.render(f5);
		this.Shape2.render(f5);
		this.Shape3.render(f5);
		this.Shape4.render(f5);
		this.Shape5.render(f5);
		this.Shape6.render(f5);
		this.Shape7.render(f5);
		this.Shape8.render(f5);
	}

	private static void setRotation(ModelRenderer model, float x, float y, float z) {

		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}
