package api.hbm.energy;

import java.util.List;

public interface IEnergySource {
	
	void ffgeuaInit();
	/**
	 * If you want the energy that is generated by the energy source
	 * to be transferred by the copper cables, use this. To use this,
	 * call the ffgeua method in {@link api.hbm.util.HbmUtils}*/
	void ffgeua(int x, int y, int z, boolean newTact);
	/**
	 * This controls how often energy gets drawn into conductors per tick*/
	boolean getTact();
	/**Returns the amount of power the tile entity has*/
	long getSPower();
	/**Sets the amount of power the tile entity has when called*/
	void setSPower(long i);
	List<IEnergyConsumer> getList();
	void clearList();
}
