package com.hbm.explosion;

import com.hbm.particles.EntitySmokeFX;

import net.minecraft.init.Blocks;
import net.minecraft.world.World;

public class ExplosionParticle {
	
	public static void spawnMush(World world, int x, int y, int z)
	{
		x -= 6;
		z -= 6;
		
		/*world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 0, (double) z + 0, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 0, (double) z + 1, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 0, (double) z + 1, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 0, (double) z + 1, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 0, (double) z + 1, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 0, (double) z + 2, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 0, (double) z + 2, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 0, (double) z + 2, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 0, (double) z + 2, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 0, (double) z + 2, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 2, (double) y + 0, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 0, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 0, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 0, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 0, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 12, (double) y + 0, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 1, (double) y + 0, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 0, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 0, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 0, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 0, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 0, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 13, (double) y + 0, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 2, (double) y + 0, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 0, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 0, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 0, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 0, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 12, (double) y + 0, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 1, (double) y + 0, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 0, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 0, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 0, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 0, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 0, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 13, (double) y + 0, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 0, (double) y + 0, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 2, (double) y + 0, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 0, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 0, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 0, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 0, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 12, (double) y + 0, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 14, (double) y + 0, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 1, (double) y + 0, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 0, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 0, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 0, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 0, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 0, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 13, (double) y + 0, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 2, (double) y + 0, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 0, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 0, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 0, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 0, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 12, (double) y + 0, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 1, (double) y + 0, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 0, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 0, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 0, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 0, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 0, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 13, (double) y + 0, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 2, (double) y + 0, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 0, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 0, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 0, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 0, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 12, (double) y + 0, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 0, (double) z + 12, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 0, (double) z + 12, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 0, (double) z + 12, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 0, (double) z + 12, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 0, (double) z + 12, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 0, (double) z + 13, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 0, (double) z + 13, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 0, (double) z + 13, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 0, (double) z + 13, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 0, (double) z + 14, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 1, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 1, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 1, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 1, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 1, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 1, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 1, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 1, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 1, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 1, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 1, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 1, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 1, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 1, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 1, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 1, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 1, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 1, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 1, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 1, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 1, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 1, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 1, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 1, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 1, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 1, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 1, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 1, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 1, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 1, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 1, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 1, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 1, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 1, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 1, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 1, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 1, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 2, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 2, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 2, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 2, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 2, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 2, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 2, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 2, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 2, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 2, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 2, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 2, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 3, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 3, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 3, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 3, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 3, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 4, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 4, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 4, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 4, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 5, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 5, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 5, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 5, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 5, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 6, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 6, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 6, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 6, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 6, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 6, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 6, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 6, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 6, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 6, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 6, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 6, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 6, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 6, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 6, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 6, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 6, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 6, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 6, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 6, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 6, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 6, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 6, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 6, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 7, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 7, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 7, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 7, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 7, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 8, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 8, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 8, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 8, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 9, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 9, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 9, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 9, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 9, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 9, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 9, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 9, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 9, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 9, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 9, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 9, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 9, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 9, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 9, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 9, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 9, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 9, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 9, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 9, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 9, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 9, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 9, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 9, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 9, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 9, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 9, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 9, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 9, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 10, (double) z + 2, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 10, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 10, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 10, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 10, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 10, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 10, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 10, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 10, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 10, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 10, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 10, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 10, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 10, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 10, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 10, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 10, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 10, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 2, (double) y + 10, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 10, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 10, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 10, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 10, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 12, (double) y + 10, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 10, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 10, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 10, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 10, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 10, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 10, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 10, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 10, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 10, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 10, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 10, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 10, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 10, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 10, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 10, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 10, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 10, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 10, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 10, (double) z + 12, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 11, (double) z + 1, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 11, (double) z + 2, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 11, (double) z + 2, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 11, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 11, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 11, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 11, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 11, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 11, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 11, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 11, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 11, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 11, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 11, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 11, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 2, (double) y + 11, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 11, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 11, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 11, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 11, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 12, (double) y + 11, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 1, (double) y + 11, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 11, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 11, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 11, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 11, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 11, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 13, (double) y + 11, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 2, (double) y + 11, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 11, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 11, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 11, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 11, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 12, (double) y + 11, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 11, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 11, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 11, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 11, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 11, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 11, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 11, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 11, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 11, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 11, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 11, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 11, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 11, (double) z + 12, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 11, (double) z + 12, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 11, (double) z + 13, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 12, (double) z + 2, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 12, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 12, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 12, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 12, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 12, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 12, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 12, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 12, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 12, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 12, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 12, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 12, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 12, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 12, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 12, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 12, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 12, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 12, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 2, (double) y + 12, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 12, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 12, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 12, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 12, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 12, (double) y + 12, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 12, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 12, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 12, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 12, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 12, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 12, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 12, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 12, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 12, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 12, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 12, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 12, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 12, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 12, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 12, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 12, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 12, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 12, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 12, (double) z + 12, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 13, (double) z + 1, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 13, (double) z + 2, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 13, (double) z + 2, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 13, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 13, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 13, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 13, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 13, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 13, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 13, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 13, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 13, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 13, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 13, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 13, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 2, (double) y + 13, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 13, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 13, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 13, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 13, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 12, (double) y + 13, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 1, (double) y + 13, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 13, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 13, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 13, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 13, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 13, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 13, (double) y + 13, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 2, (double) y + 13, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 13, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 13, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 13, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 13, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 12, (double) y + 13, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 13, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 13, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 13, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 13, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 13, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 13, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 13, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 13, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 13, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 13, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 13, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 13, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 13, (double) z + 12, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 13, (double) z + 12, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 13, (double) z + 13, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 14, (double) z + 2, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 14, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 14, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 14, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 14, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 14, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 14, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 14, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 14, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 14, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 14, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 14, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 14, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 14, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 14, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 14, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 14, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 14, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 14, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 2, (double) y + 14, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 14, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 14, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 14, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 14, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 12, (double) y + 14, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 14, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 14, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 14, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 14, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 14, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 14, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 14, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 14, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 14, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 14, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 14, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 14, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 14, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 14, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 14, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 14, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 14, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 14, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 14, (double) z + 12, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 15, (double) z + 3, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 15, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 15, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 15, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 15, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 15, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 15, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 15, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 15, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 15, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 3, (double) y + 15, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 15, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 15, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 15, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 11, (double) y + 15, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 15, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 15, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 15, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 15, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 15, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 15, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 15, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 15, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 15, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 15, (double) z + 11, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 16, (double) z + 4, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 16, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 16, (double) z + 5, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 16, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 16, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 16, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 4, (double) y + 16, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 16, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 16, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 10, (double) y + 16, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 5, (double) y + 16, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 16, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 9, (double) y + 16, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 16, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 16, (double) z + 9, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 16, (double) z + 10, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 17, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 17, (double) z + 6, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 7, (double) y + 17, (double) z + 7, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 6, (double) y + 17, (double) z + 8, 0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, (double)x + 8, (double) y + 17, (double) z + 8, 0.0, 0.0, 0.0));*/
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 3, y + 0, z + 0,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 5, y + 0, z + 0,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 7, y + 0, z + 0,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 9, y + 0, z + 0,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 0, y + 0, z + 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 12, y + 0, z + 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 5, y + 0, z + 4,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 7, y + 0, z + 4,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 0, y + 0, z + 5,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 4, y + 0, z + 5,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 8, y + 0, z + 5,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 12, y + 0, z + 5,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 0, y + 0, z + 7,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 4, y + 0, z + 7,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 8, y + 0, z + 7,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 12, y + 0, z + 7,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 5, y + 0, z + 8,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 7, y + 0, z + 8,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 0, y + 0, z + 9,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 12, y + 0, z + 9,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 3, y + 0, z + 12,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 5, y + 0, z + 12,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 7, y + 0, z + 12,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 9, y + 0, z + 12,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 4, y + 1, z + 2,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 6, y + 1, z + 2,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 8, y + 1, z + 2,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 9, y + 1, z + 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 2, y + 1, z + 4,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 10, y + 1, z + 4,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 2, y + 1, z + 6,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 10, y + 1, z + 6,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 2, y + 1, z + 8,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 10, y + 1, z + 8,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 4, y + 1, z + 10,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 6, y + 1, z + 10,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 8, y + 1, z + 10,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 5, y + 2, z + 4,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 7, y + 2, z + 4,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 4, y + 2, z + 5,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 8, y + 2, z + 5,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 4, y + 2, z + 7,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 8, y + 2, z + 7,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 5, y + 2, z + 8,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 7, y + 2, z + 8,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 6, y + 4, z + 5,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 5, y + 4, z + 6,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 7, y + 4, z + 6,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 6, y + 4, z + 7,0.0, 0.0, 0.0));
		y += 2;
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 6, y + 4, z + 5,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 5, y + 4, z + 6,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 7, y + 4, z + 6,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 6, y + 4, z + 7,0.0, 0.0, 0.0));
		
		/*world.spawnEntityInWorld(new EntitySmokeFX(world, x + 4, y + 6, z + 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 8, y + 6, z + 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 3, y + 6, z + 4,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 9, y + 6, z + 4,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 3, y + 6, z + 8,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 9, y + 6, z + 8,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 4, y + 6, z + 9,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 8, y + 6, z + 9,0.0, 0.0, 0.0));*/
		y--;
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 5, y + 7, z + 5,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 7, y + 7, z + 5,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 5, y + 7, z + 7,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 7, y + 7, z + 7,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 6, y + 8, z + 6,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 6, y + 9, z + 2,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 4, y + 9, z + 4,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 8, y + 9, z + 4,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 2, y + 9, z + 6,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 8, y + 9, z + 6,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 10, y + 9, z + 6,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 4, y + 9, z + 8,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 8, y + 9, z + 8,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 6, y + 9, z + 10,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 3, y + 10, z + 2,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 9, y + 10, z + 2,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 2, y + 10, z + 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 6, y + 10, z + 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 10, y + 10, z + 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 2, y + 10, z + 9,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 10, y + 10, z + 9,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 3, y + 10, z + 10,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 9, y + 10, z + 10,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 6, y + 11, z + 0,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 5, y + 11, z + 5,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 7, y + 11, z + 5,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 0, y + 11, z + 6,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 12, y + 11, z + 6,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 5, y + 11, z + 7,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 7, y + 11, z + 7,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 6, y + 11, z + 12,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 3, y + 12, z + 2,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 5, y + 12, z + 2,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 7, y + 12, z + 2,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 9, y + 12, z + 2,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 2, y + 12, z + 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 10, y + 12, z + 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 2, y + 12, z + 5,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 10, y + 12, z + 5,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 2, y + 12, z + 7,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 10, y + 12, z + 7,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 2, y + 12, z + 9,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 10, y + 12, z + 9,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 3, y + 12, z + 10,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 5, y + 12, z + 10,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 7, y + 12, z + 10,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 9, y + 12, z + 10,0.0, 0.0, 0.0));
		//
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 3, y + 12, z + 2 - 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 5, y + 12, z + 2 - 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 7, y + 12, z + 2 - 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 9, y + 12, z + 2 - 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 2 - 3, y + 12, z + 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 10 + 3, y + 12, z + 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 2 - 3, y + 12, z + 5,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 10 + 3, y + 12, z + 5,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 2 - 3, y + 12, z + 7,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 10 + 3, y + 12, z + 7,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 2 - 3, y + 12, z + 9,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 10 + 3, y + 12, z + 9,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 3, y + 12, z + 10 + 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 5, y + 12, z + 10 + 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 7, y + 12, z + 10 + 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 9, y + 12, z + 10 + 3,0.0, 0.0, 0.0));
		//
		y -= 2;
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 3, y + 12, z + 2 - 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 5, y + 12, z + 2 - 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 7, y + 12, z + 2 - 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 9, y + 12, z + 2 - 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 2 - 3, y + 12, z + 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 10 + 3, y + 12, z + 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 2 - 3, y + 12, z + 5,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 10 + 3, y + 12, z + 5,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 2 - 3, y + 12, z + 7,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 10 + 3, y + 12, z + 7,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 2 - 3, y + 12, z + 9,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 10 + 3, y + 12, z + 9,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 3, y + 12, z + 10 + 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 5, y + 12, z + 10 + 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 7, y + 12, z + 10 + 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 9, y + 12, z + 10 + 3,0.0, 0.0, 0.0));
		y += 2;
		//
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 6, y + 13, z + 0,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 0, y + 13, z + 6,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 12, y + 13, z + 6,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 6, y + 13, z + 12,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 3, y + 14, z + 2,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 9, y + 14, z + 2,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 2, y + 14, z + 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 10, y + 14, z + 3,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 6, y + 14, z + 5,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 5, y + 14, z + 6,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 7, y + 14, z + 6,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 6, y + 14, z + 7,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 2, y + 14, z + 9,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 10, y + 14, z + 9,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 3, y + 14, z + 10,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 9, y + 14, z + 10,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 6, y + 15, z + 2,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 4, y + 15, z + 4,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 8, y + 15, z + 4,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 2, y + 15, z + 6,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 10, y + 15, z + 6,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 4, y + 15, z + 8,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 8, y + 15, z + 8,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 6, y + 15, z + 10,0.0, 0.0, 0.0));
		/*world.spawnEntityInWorld(new EntitySmokeFX(world, x + 5, y + 17, z + 5,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 7, y + 17, z + 5,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 5, y + 17, z + 7,0.0, 0.0, 0.0));
		world.spawnEntityInWorld(new EntitySmokeFX(world, x + 7, y + 17, z + 7,0.0, 0.0, 0.0));*/



	}

}
