// Date: 18.05.2015 21:04:52
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.hbm.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTestBombAdvanced extends ModelBase
{
  //fields
    ModelRenderer FinEnd;
    ModelRenderer BombTip;
    ModelRenderer FinBase;
    ModelRenderer FinTop;
    ModelRenderer FinBottom;
    ModelRenderer FinLeft;
    ModelRenderer FinRight;
    ModelRenderer BombBody;
  
  public ModelTestBombAdvanced()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      FinEnd = new ModelRenderer(this, 0, 0);
      FinEnd.addBox(0F, 0F, 0F, 8, 8, 4);
      FinEnd.setRotationPoint(-4F, 16F, 20F);
      FinEnd.setTextureSize(128, 128);
      FinEnd.mirror = true;
      setRotation(FinEnd, 0F, 0F, 0F);
      BombTip = new ModelRenderer(this, 55, 0);
      BombTip.addBox(0F, 0F, 0F, 6, 6, 2);
      BombTip.setRotationPoint(-3F, 17F, -24F);
      BombTip.setTextureSize(128, 128);
      BombTip.mirror = true;
      setRotation(BombTip, 0F, 0F, 0F);
      FinBase = new ModelRenderer(this, 74, 0);
      FinBase.addBox(0F, 0F, 0F, 6, 6, 2);
      FinBase.setRotationPoint(-3F, 17F, 14F);
      FinBase.setTextureSize(128, 128);
      FinBase.mirror = true;
      setRotation(FinBase, 0F, 0F, 0F);
      FinTop = new ModelRenderer(this, 0, 74);
      FinTop.addBox(0F, 0F, -6F, 8, 0, 6);
      FinTop.setRotationPoint(-4F, 16F, 20F);
      FinTop.setTextureSize(128, 128);
      FinTop.mirror = true;
      setRotation(FinTop, 0.4363323F, 0F, 0F);
      FinBottom = new ModelRenderer(this, 0, 74);
      FinBottom.addBox(0F, 0F, -6F, 8, 0, 6);
      FinBottom.setRotationPoint(-4F, 24F, 20F);
      FinBottom.setTextureSize(128, 128);
      FinBottom.mirror = true;
      setRotation(FinBottom, -0.4363323F, 0F, 0F);
      FinLeft = new ModelRenderer(this, 0, 51);
      FinLeft.addBox(0F, 0F, -6F, 0, 8, 6);
      FinLeft.setRotationPoint(4F, 16F, 20F);
      FinLeft.setTextureSize(128, 128);
      FinLeft.mirror = true;
      setRotation(FinLeft, 0F, 0.4363323F, 0F);
      FinRight = new ModelRenderer(this, 0, 51);
      FinRight.addBox(0F, 0F, -6F, 0, 8, 6);
      FinRight.setRotationPoint(-4F, 16F, 20F);
      FinRight.setTextureSize(128, 128);
      FinRight.mirror = true;
      setRotation(FinRight, 0F, -0.4363323F, 0F);
      BombBody = new ModelRenderer(this, 0, 0);
      BombBody.addBox(0F, 0F, 0F, 8, 8, 36);
      BombBody.setRotationPoint(-4F, 16F, -22F);
      BombBody.setTextureSize(128, 128);
      BombBody.mirror = true;
      setRotation(BombBody, 0F, 0F, 0F);
  }
  
  @Override
public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    FinEnd.render(f5);
    BombTip.render(f5);
    FinBase.render(f5);
    FinTop.render(f5);
    FinBottom.render(f5);
    FinLeft.render(f5);
    FinRight.render(f5);
    BombBody.render(f5);
  }
  
  public void renderModel(float f)
  {
    FinEnd.render(f);
    BombTip.render(f);
    FinBase.render(f);
    FinTop.render(f);
    FinBottom.render(f);
    FinLeft.render(f);
    FinRight.render(f);
    BombBody.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  @Override
public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
