// Date: 29.08.2016 12:31:19
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.hbm.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelMP extends ModelBase {
	// fields
	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Shape3;
	ModelRenderer Shape4;
	ModelRenderer Shape5;
	ModelRenderer Shape6;
	ModelRenderer Shape7;
	ModelRenderer Shape8;
	ModelRenderer Shape9;
	ModelRenderer Shape10;
	ModelRenderer Shape11;
	ModelRenderer Shape12;
	ModelRenderer Shape13;
	ModelRenderer Shape14;
	ModelRenderer Shape15;
	ModelRenderer Shape16;
	ModelRenderer Shape17;
	ModelRenderer Shape18;
	ModelRenderer Shape19;
	ModelRenderer Shape20;
	ModelRenderer Shape21;
	ModelRenderer Shape22;
	ModelRenderer Shape23;
	ModelRenderer Shape24;
	ModelRenderer Shape25;

	public ModelMP() {
		textureWidth = 128;
		textureHeight = 64;

		Shape1 = new ModelRenderer(this, 0, 0);
		Shape1.addBox(0F, 0F, 0F, 3, 6, 1);
		Shape1.setRotationPoint(-25F, -3F, -2F);
		Shape1.setTextureSize(128, 64);
		Shape1.mirror = true;
		setRotation(Shape1, 0F, 0F, 0F);
		Shape2 = new ModelRenderer(this, 8, 0);
		Shape2.addBox(0F, 0F, 0F, 3, 6, 1);
		Shape2.setRotationPoint(-25F, -3F, 2F);
		Shape2.setTextureSize(128, 64);
		Shape2.mirror = true;
		setRotation(Shape2, 0F, 0F, 0F);
		Shape3 = new ModelRenderer(this, 0, 8);
		Shape3.addBox(0F, 0F, 0F, 2, 3, 3);
		Shape3.setRotationPoint(-24F, 0F, -1F);
		Shape3.setTextureSize(128, 64);
		Shape3.mirror = true;
		setRotation(Shape3, 0F, 0F, 0F);
		Shape4 = new ModelRenderer(this, 0, 14);
		Shape4.addBox(0F, 0F, 0F, 20, 3, 1);
		Shape4.setRotationPoint(-22F, -3F, -2F);
		Shape4.setTextureSize(128, 64);
		Shape4.mirror = true;
		setRotation(Shape4, 0F, 0F, 0F);
		Shape5 = new ModelRenderer(this, 0, 18);
		Shape5.addBox(0F, 0F, 0F, 20, 3, 1);
		Shape5.setRotationPoint(-22F, -3F, 2F);
		Shape5.setTextureSize(128, 64);
		Shape5.mirror = true;
		setRotation(Shape5, 0F, 0F, 0F);
		Shape6 = new ModelRenderer(this, 0, 22);
		Shape6.addBox(0F, 0F, 0F, 24, 1, 3);
		Shape6.setRotationPoint(-24F, -1F, -1F);
		Shape6.setTextureSize(128, 64);
		Shape6.mirror = true;
		setRotation(Shape6, 0F, 0F, 0F);
		Shape7 = new ModelRenderer(this, 0, 26);
		Shape7.addBox(0F, 0F, 0F, 26, 4, 5);
		Shape7.setRotationPoint(-25F, 3F, -2F);
		Shape7.setTextureSize(128, 64);
		Shape7.mirror = true;
		setRotation(Shape7, 0F, 0F, 0F);
		Shape8 = new ModelRenderer(this, 16, 0);
		Shape8.addBox(0F, 0F, 0F, 3, 6, 1);
		Shape8.setRotationPoint(-2F, -3F, -2F);
		Shape8.setTextureSize(128, 64);
		Shape8.mirror = true;
		setRotation(Shape8, 0F, 0F, 0F);
		Shape9 = new ModelRenderer(this, 24, 0);
		Shape9.addBox(0F, 0F, 0F, 3, 6, 1);
		Shape9.setRotationPoint(-2F, -3F, 2F);
		Shape9.setTextureSize(128, 64);
		Shape9.mirror = true;
		setRotation(Shape9, 0F, 0F, 0F);
		Shape10 = new ModelRenderer(this, 90, 22);
		Shape10.addBox(0F, 0F, 0F, 11, 3, 3);
		Shape10.setRotationPoint(-2F, 0F, -1F);
		Shape10.setTextureSize(128, 64);
		Shape10.mirror = true;
		setRotation(Shape10, 0F, 0F, 0F);
		Shape11 = new ModelRenderer(this, 19, 38);
		Shape11.addBox(0F, 0F, 0F, 26, 1, 4);
		Shape11.setRotationPoint(-25F, 7F, -1.5F);
		Shape11.setTextureSize(128, 64);
		Shape11.mirror = true;
		setRotation(Shape11, 0F, 0F, 0F);
		Shape12 = new ModelRenderer(this, 78, 35);
		Shape12.addBox(0F, 0F, 0F, 20, 5, 5);
		Shape12.setRotationPoint(-25F, 8F, -2F);
		Shape12.setTextureSize(128, 64);
		Shape12.mirror = true;
		setRotation(Shape12, 0F, 0F, 0F);
		Shape13 = new ModelRenderer(this, 54, 45);
		Shape13.addBox(0F, 0F, 0F, 32, 2, 5);
		Shape13.setRotationPoint(-5F, 8F, -2F);
		Shape13.setTextureSize(128, 64);
		Shape13.mirror = true;
		setRotation(Shape13, 0F, 0F, 0F);
		Shape14 = new ModelRenderer(this, 108, 28);
		Shape14.addBox(0F, -6F, 0F, 8, 6, 1);
		Shape14.setRotationPoint(1F, 8F, -2F);
		Shape14.setTextureSize(128, 64);
		Shape14.mirror = true;
		setRotation(Shape14, -0.0872665F, 0F, 0F);
		Shape15 = new ModelRenderer(this, 84, 52);
		Shape15.addBox(0F, 0F, 0F, 18, 9, 3);
		Shape15.setRotationPoint(9F, -1F, -1F);
		Shape15.setTextureSize(128, 64);
		Shape15.mirror = true;
		setRotation(Shape15, 0F, 0F, 0F);
		Shape16 = new ModelRenderer(this, 0, 43);
		Shape16.addBox(0F, -9F, 0F, 18, 9, 1);
		Shape16.setRotationPoint(9F, 8F, -2F);
		Shape16.setTextureSize(128, 64);
		Shape16.mirror = true;
		setRotation(Shape16, -0.0872665F, 0F, 0F);
		Shape17 = new ModelRenderer(this, 90, 28);
		Shape17.addBox(0F, -6F, -1F, 8, 6, 1);
		Shape17.setRotationPoint(1F, 8F, 3F);
		Shape17.setTextureSize(128, 64);
		Shape17.mirror = true;
		setRotation(Shape17, 0.0872665F, 0F, 0F);
		Shape18 = new ModelRenderer(this, 46, 54);
		Shape18.addBox(0F, -9F, -1F, 18, 9, 1);
		Shape18.setRotationPoint(9F, 8F, 3F);
		Shape18.setTextureSize(128, 64);
		Shape18.mirror = true;
		setRotation(Shape18, 0.0872665F, 0F, 0F);
		Shape19 = new ModelRenderer(this, 0, 35);
		Shape19.addBox(0F, -3F, 0F, 4, 3, 5);
		Shape19.setRotationPoint(-5F, 13F, -2F);
		Shape19.setTextureSize(128, 64);
		Shape19.mirror = true;
		setRotation(Shape19, 0F, 0F, -0.8726646F);
		Shape20 = new ModelRenderer(this, 0, 53);
		Shape20.addBox(0F, 0F, 0F, 18, 6, 5);
		Shape20.setRotationPoint(9F, 10F, -2F);
		Shape20.setTextureSize(128, 64);
		Shape20.mirror = true;
		setRotation(Shape20, 0F, 0F, 0F);
		Shape21 = new ModelRenderer(this, 42, 16);
		Shape21.addBox(0F, 0F, 0F, 3, 5, 1);
		Shape21.setRotationPoint(1F, 10F, 0F);
		Shape21.setTextureSize(128, 64);
		Shape21.mirror = true;
		setRotation(Shape21, 0F, 0F, 0F);
		Shape22 = new ModelRenderer(this, 62, 27);
		Shape22.addBox(0F, 0F, 0F, 11, 1, 3);
		Shape22.setRotationPoint(-2F, 15F, -1F);
		Shape22.setTextureSize(128, 64);
		Shape22.mirror = true;
		setRotation(Shape22, 0F, 0F, 0F);
		Shape23 = new ModelRenderer(this, 62, 31);
		Shape23.addBox(-6F, -1F, 0F, 6, 1, 3);
		Shape23.setRotationPoint(-2F, 16F, -1F);
		Shape23.setTextureSize(128, 64);
		Shape23.mirror = true;
		setRotation(Shape23, 0F, 0F, 0.5235988F);
		Shape24 = new ModelRenderer(this, 20, 10);
		Shape24.addBox(0F, 0F, 0F, 2, 1, 3);
		Shape24.setRotationPoint(-21F, -2F, -1F);
		Shape24.setTextureSize(128, 64);
		Shape24.mirror = true;
		setRotation(Shape24, 0F, 0F, 0F);
		Shape25 = new ModelRenderer(this, 10, 10);
		Shape25.addBox(0F, 0F, 0F, 2, 1, 3);
		Shape25.setRotationPoint(-5F, -2F, -1F);
		Shape25.setTextureSize(128, 64);
		Shape25.mirror = true;
		setRotation(Shape25, 0F, 0F, 0F);
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Shape1.render(f5);
		Shape2.render(f5);
		Shape3.render(f5);
		Shape4.render(f5);
		Shape5.render(f5);
		Shape6.render(f5);
		Shape7.render(f5);
		Shape8.render(f5);
		Shape9.render(f5);
		Shape10.render(f5);
		Shape11.render(f5);
		Shape12.render(f5);
		Shape13.render(f5);
		Shape14.render(f5);
		Shape15.render(f5);
		Shape16.render(f5);
		Shape17.render(f5);
		Shape18.render(f5);
		Shape19.render(f5);
		Shape20.render(f5);
		Shape21.render(f5);
		Shape22.render(f5);
		Shape23.render(f5);
		Shape24.render(f5);
		Shape25.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

}
