// Date: 29.08.2016 09:41:02
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.hbm.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelOSIPR extends ModelBase {
	// fields
	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Shape3;
	ModelRenderer Shape4;
	ModelRenderer Shape5;
	ModelRenderer Shape6;
	ModelRenderer Shape7;
	ModelRenderer Shape8;
	ModelRenderer Shape9;
	ModelRenderer Shape10;
	ModelRenderer Shape11;
	ModelRenderer Shape12;
	ModelRenderer Shape13;
	ModelRenderer Shape14;
	ModelRenderer Shape15;
	ModelRenderer Shape16;
	ModelRenderer Shape17;
	ModelRenderer Shape18;
	ModelRenderer Shape19;
	ModelRenderer Shape20;
	ModelRenderer Shape21;
	ModelRenderer Shape22;
	ModelRenderer Shape23;

	public ModelOSIPR() {
		textureWidth = 64;
		textureHeight = 64;

		Shape1 = new ModelRenderer(this, 0, 0);
		Shape1.addBox(0F, 0F, 0F, 8, 3, 3);
		Shape1.setRotationPoint(0F, 0F, -0.5F);
		Shape1.setTextureSize(64, 64);
		Shape1.mirror = true;
		setRotation(Shape1, 0F, 0F, 0F);
		Shape2 = new ModelRenderer(this, 0, 6);
		Shape2.addBox(0F, 0F, 0F, 11, 2, 2);
		Shape2.setRotationPoint(8F, 0F, 0F);
		Shape2.setTextureSize(64, 64);
		Shape2.mirror = true;
		setRotation(Shape2, 0F, 0F, 0F);
		Shape3 = new ModelRenderer(this, 0, 10);
		Shape3.addBox(0F, 0F, 0F, 2, 3, 2);
		Shape3.setRotationPoint(17F, 2F, 0F);
		Shape3.setTextureSize(64, 64);
		Shape3.mirror = true;
		setRotation(Shape3, 0F, 0F, 0F);
		Shape4 = new ModelRenderer(this, 0, 15);
		Shape4.addBox(-5F, -3F, 0F, 5, 3, 2);
		Shape4.setRotationPoint(17F, 5F, 0F);
		Shape4.setTextureSize(64, 64);
		Shape4.mirror = true;
		setRotation(Shape4, 0F, 0F, 0.4363323F);
		Shape5 = new ModelRenderer(this, 8, 10);
		Shape5.addBox(-8F, -1F, 0F, 3, 1, 2);
		Shape5.setRotationPoint(17F, 5F, 0F);
		Shape5.setTextureSize(64, 64);
		Shape5.mirror = true;
		setRotation(Shape5, 0F, 0F, 0.4363323F);
		Shape6 = new ModelRenderer(this, 30, 0);
		Shape6.addBox(0F, 0F, 0F, 10, 2, 2);
		Shape6.setRotationPoint(-10F, 0.5F, 0F);
		Shape6.setTextureSize(64, 64);
		Shape6.mirror = true;
		setRotation(Shape6, 0F, 0F, 0F);
		Shape7 = new ModelRenderer(this, 54, 0);
		Shape7.addBox(0F, 0F, 0F, 3, 2, 1);
		Shape7.setRotationPoint(-13F, 0.5F, 0.5F);
		Shape7.setTextureSize(64, 64);
		Shape7.mirror = true;
		setRotation(Shape7, 0F, 0F, 0F);
		Shape8 = new ModelRenderer(this, 30, 4);
		Shape8.addBox(0F, 0F, 0F, 10, 3, 3);
		Shape8.setRotationPoint(-16F, 2F, -0.5F);
		Shape8.setTextureSize(64, 64);
		Shape8.mirror = true;
		setRotation(Shape8, 0F, 0F, 0F);
		Shape9 = new ModelRenderer(this, 30, 10);
		Shape9.addBox(0F, 0F, 0F, 3, 1, 3);
		Shape9.setRotationPoint(-19F, 4F, -0.5F);
		Shape9.setTextureSize(64, 64);
		Shape9.mirror = true;
		setRotation(Shape9, 0F, 0F, 0F);
		Shape10 = new ModelRenderer(this, 42, 10);
		Shape10.addBox(0F, 0F, 0F, 3, 1, 3);
		Shape10.setRotationPoint(-19F, 2F, -0.5F);
		Shape10.setTextureSize(64, 64);
		Shape10.mirror = true;
		setRotation(Shape10, 0F, 0F, 0F);
		Shape11 = new ModelRenderer(this, 0, 20);
		Shape11.addBox(0F, 0F, 0F, 1, 1, 2);
		Shape11.setRotationPoint(8F, -1F, 0F);
		Shape11.setTextureSize(64, 64);
		Shape11.mirror = true;
		setRotation(Shape11, 0F, 0F, 0F);
		Shape12 = new ModelRenderer(this, 30, 14);
		Shape12.addBox(0F, 0F, 0F, 7, 3, 2);
		Shape12.setRotationPoint(0F, 3F, 0F);
		Shape12.setTextureSize(64, 64);
		Shape12.mirror = true;
		setRotation(Shape12, 0F, 0F, 0F);
		Shape13 = new ModelRenderer(this, 30, 19);
		Shape13.addBox(0F, -2F, 0F, 5, 2, 2);
		Shape13.setRotationPoint(7F, 6F, 0F);
		Shape13.setTextureSize(64, 64);
		Shape13.mirror = true;
		setRotation(Shape13, 0F, 0F, -0.9599311F);
		Shape14 = new ModelRenderer(this, 30, 23);
		Shape14.addBox(0F, 0F, 0F, 2, 5, 1);
		Shape14.setRotationPoint(5F, 6F, 0.5F);
		Shape14.setTextureSize(64, 64);
		Shape14.mirror = true;
		setRotation(Shape14, 0F, 0F, -0.3490659F);
		Shape15 = new ModelRenderer(this, 0, 23);
		Shape15.addBox(0F, 0F, 0F, 7, 2, 1);
		Shape15.setRotationPoint(-6F, 5F, 0.5F);
		Shape15.setTextureSize(64, 64);
		Shape15.mirror = true;
		setRotation(Shape15, 0F, 0F, 0F);
		Shape16 = new ModelRenderer(this, 0, 26);
		Shape16.addBox(0F, 0F, 0F, 8, 1, 2);
		Shape16.setRotationPoint(-6F, 7F, 0F);
		Shape16.setTextureSize(64, 64);
		Shape16.mirror = true;
		setRotation(Shape16, 0F, 0F, 0F);
		Shape17 = new ModelRenderer(this, 0, 29);
		Shape17.addBox(0F, 0F, 0F, 3, 6, 6);
		Shape17.setRotationPoint(-9F, 9F, -3F);
		Shape17.setTextureSize(64, 64);
		Shape17.mirror = true;
		setRotation(Shape17, 0.6108652F, 0F, 0F);
		Shape18 = new ModelRenderer(this, 0, 41);
		Shape18.addBox(0F, 0F, 0F, 3, 6, 7);
		Shape18.setRotationPoint(-9F, 8F, -4F);
		Shape18.setTextureSize(64, 64);
		Shape18.mirror = true;
		setRotation(Shape18, 0F, 0F, 0F);
		Shape19 = new ModelRenderer(this, 30, 29);
		Shape19.addBox(0F, 1F, 6F, 2, 4, 3);
		Shape19.setRotationPoint(-8.5F, 9F, -3F);
		Shape19.setTextureSize(64, 64);
		Shape19.mirror = true;
		setRotation(Shape19, 0.6108652F, 0F, 0F);
		Shape20 = new ModelRenderer(this, 30, 36);
		Shape20.addBox(0F, 0F, 0F, 1, 6, 3);
		Shape20.setRotationPoint(-8F, 1F, 3F);
		Shape20.setTextureSize(64, 64);
		Shape20.mirror = true;
		setRotation(Shape20, 0F, 0F, 0F);
		Shape21 = new ModelRenderer(this, 30, 45);
		Shape21.addBox(0F, -3F, 0F, 1, 5, 4);
		Shape21.setRotationPoint(-8F, 2F, 3F);
		Shape21.setTextureSize(64, 64);
		Shape21.mirror = true;
		setRotation(Shape21, 0.9599311F, 0F, 0F);
		Shape22 = new ModelRenderer(this, 0, 54);
		Shape22.addBox(0F, 0F, 0F, 2, 2, 2);
		Shape22.setRotationPoint(-11F, 7F, 0F);
		Shape22.setTextureSize(64, 64);
		Shape22.mirror = true;
		setRotation(Shape22, 0F, 0F, 0F);
		Shape23 = new ModelRenderer(this, 0, 58);
		Shape23.addBox(-7F, -2F, 0F, 7, 2, 2);
		Shape23.setRotationPoint(-11F, 9F, 0F);
		Shape23.setTextureSize(64, 64);
		Shape23.mirror = true;
		setRotation(Shape23, 0F, 0F, 0.148353F);
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Shape1.render(f5);
		Shape2.render(f5);
		Shape3.render(f5);
		Shape4.render(f5);
		Shape5.render(f5);
		Shape6.render(f5);
		Shape7.render(f5);
		Shape8.render(f5);
		Shape9.render(f5);
		Shape10.render(f5);
		Shape11.render(f5);
		Shape12.render(f5);
		Shape13.render(f5);
		Shape14.render(f5);
		Shape15.render(f5);
		Shape16.render(f5);
		Shape17.render(f5);
		Shape18.render(f5);
		Shape19.render(f5);
		Shape20.render(f5);
		Shape21.render(f5);
		Shape22.render(f5);
		Shape23.render(f5);
	}

	public void renderAll(float f5) {
		Shape1.render(f5);
		Shape2.render(f5);
		Shape3.render(f5);
		Shape4.render(f5);
		Shape5.render(f5);
		Shape6.render(f5);
		Shape7.render(f5);
		Shape8.render(f5);
		Shape9.render(f5);
		Shape10.render(f5);
		Shape11.render(f5);
		Shape12.render(f5);
		Shape13.render(f5);
		Shape14.render(f5);
		Shape15.render(f5);
		Shape16.render(f5);
		Shape17.render(f5);
		Shape18.render(f5);
		Shape19.render(f5);
		Shape20.render(f5);
		Shape21.render(f5);
		Shape22.render(f5);
		Shape23.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
